### ISSUE TITLE
rxvt-unicode-patched don't work anymore. [Bug]

### ISSUE THREAD

**Issue by linuxmobile** [owl4ce/dotfiles#105]
It's impossible to install it now. 

Error: failure while downloading http://dist.schmorp.de/rxvt-unicode/rxvt-unicode-9.22.tar.bz2 aborting

**Comment by owl4ce** [comment]
Yeah, the rxvt-unicode-patched in the AUR should be updated from 9.22 to 9.26.
http://dist.schmorp.de/rxvt-unicode/

Actually, can use rxvt-unicode (no AUR) but you should enable letterspace to -1 in ~/.Xresources.

**Comment by linuxmobile** [comment]
> , can use rxvt-unicode (no AUR) but you should enable **letterspace** to **-1** in `~/.`

Thx for fast reply!!!! I love your work :)

**Comment by ledleledle** [comment]
this should work
https://aur.archlinux.org/packages/rxvt-unicode-pixbuf-patched

**Comment by owl4ce** [comment]
Yow, but we have no problems with `rxvt-unicode`.

**Comment by ledleledle** [comment]
aight man. just in case maybe someone want to use AUR package

**Comment by owl4ce** [comment]
Use this, this is pretty damn good.
https://aur.archlinux.org/packages/rxvt-unicode-truecolor-wide-glyphs/

**Comment by ledleledle** [comment]
well... if u suggest it, i will try that

**Comment by Haritronic909** [comment]
> It's impossible to install it now.
> 
> Error: failure while downloading http://dist.schmorp.de/rxvt-unicode/rxvt-unicode-9.22.tar.bz2 aborting

Could you try using the same package after installing any code font like adobe-source-code-pro-fonts. I had some problems with urxvt i3 and arch linux. I think urxvt misses some code font to work nowadays

**Comment by Piliponful** [comment]
> **Use this, pretty damn good.** https://aur.archlinux.org/packages/rxvt-unicode-truecolor-wide-glyphs/
> 
> It supports true color emoji by using `libxft-bgra`.
> 
> ![](https://user-images.githubusercontent.com/53987136/125056679-ab805380-e0d2-11eb-8b18-84acf17c000d.png)

It worked pretty well for me, but had strange issue with font size while I input commands
