### ISSUE TITLE
Monitor Settings Error (Invalid ouput from pipe-menu...)

### ISSUE THREAD

**Issue by izumikyouta** [owl4ce/dotfiles#110]
Hi! 
So after doing a fresh install of arch and your dotfiles, when I right click on the desktop and hover over monitor settings this shows up. 

Invalid output from pipe-menu "/home/izaya/.config/openbox/pipe-menu/ob-randr.py" 

I tried looking it up online but I'm not exactly sure what the problem is here.

**Comment by FlyingCat-X** [comment]
I think you need to install the package `xorg-xrandr`

**Comment by izumikyouta** [comment]
Thanks! It did the trick.
