### ISSUE TITLE
[NEED HELP] A way to start session with HDMI/VGA off

### ISSUE THREAD

**Issue by linuxmobile** [owl4ce/dotfiles#114]
Hi Owl4ce, i love your work. I want to ask if there are a way to start session with HDMI or VGA off? Everytime it start with the session. And i won't it! Can you help me?

**Comment by owl4ce** [comment]
I don't really understand what you mean, can you explain more than as you said above?

**Comment by owl4ce** [comment]
Closed, since no response.
