### ISSUE TITLE
vscode garbled terminal font

### ISSUE THREAD

**Issue by choisiulun** [owl4ce/dotfiles#117]
Sorry for a silly question, I'm a newbie on Linux.  I have found a problem which is garbled output in my vscode terminal. But with urxvt terminal, it's fine.
![image](https://user-images.githubusercontent.com/36674999/124643542-c7fa7100-dec3-11eb-9fff-f17432429f91.png)
Should I change the Font Family of vscode? If yes, what font should I use?

**Comment by owl4ce** [comment]
> Sorry for a silly question, I'm a newbie on Linux. I have found a problem which is garbled output in my vscode terminal. But with urxvt terminal, it's fine.
> ![image](https://user-images.githubusercontent.com/36674999/124643542-c7fa7100-dec3-11eb-9fff-f17432429f91.png)
> Should I change the Font Family of vscode? If yes, what font should I use?

I don't really know about vscode related issue, but basically my zsh theme uses `Nerd Fonts` family

**Comment by owl4ce** [comment]
@choisiulun 
https://github.com/microsoft/vscode/issues/81497

**Comment by choisiulun** [comment]
Thank you so much! You are really kind! It works for me by changing font family to mplus Nerd Font.
