### ISSUE TITLE
gnome-keyring troubleshooting (systemd) [optional]

### ISSUE THREAD

**Issue by chlasswg26** [owl4ce/dotfiles#128]
Biasanya public package yang ada di github hanya tersedia rilisan debiannya saja (.deb) atau yang biasa menggunakan package arch linux bernama (**debtap**) oleh karena itu beberapa masalah muncul dan yang paling sering adalah notif gagal login atau PAM auth failure (vscode-bin aur, github-desktop.deb from github source)

1. Add the following line to /etc/pam.d/login (I guess the leading dash is important):
```cfg
auth      optional     pam_gnome_keyring.so
session    optional     pam_gnome_keyring.so        auto_start
```

2. Add the following line to /etc/pam.d/passwd:
```cfg
password      optional        pam_gnome_keyring.so
```

3. Add these lines to ~/.xinitrc:
```cfg
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
```

![2021-08-14-135941_577x346_scrot](https://user-images.githubusercontent.com/28286878/129438230-434e04ce-0827-49c4-ab1d-fecca54a9bd2.png)
![2021-08-14-140025_582x344_scrot](https://user-images.githubusercontent.com/28286878/129438235-e749a1e9-5f75-4200-8132-5434cb4c7449.png)
![2021-08-14-140037_579x345_scrot](https://user-images.githubusercontent.com/28286878/129438237-6bd14c35-8177-465d-88e6-47e9f9bacf9f.png)

Sumber : 

- [https://github.com/MicrosoftDocs/live-share/issues/213#issuecomment-383326750](https://github.com/MicrosoftDocs/live-share/issues/213#issuecomment-383326750)
- [https://github.com/MicrosoftDocs/live-share/issues/213](https://github.com/MicrosoftDocs/live-share/issues/213)

**Comment by owl4ce** [comment]
Duplicate https://github.com/owl4ce/dotfiles/issues/129, deprecating first issue.
