### ISSUE TITLE
gnome-keyring troubleshooting (systemd) [Feature Req]

### ISSUE THREAD

**Issue by chlasswg26** [owl4ce/dotfiles#129]
Biasanya public package yang ada di github hanya tersedia rilisan debiannya saja (.deb) atau yang biasa menggunakan package arch linux bernama (**debtap**) oleh karena itu beberapa masalah muncul dan yang paling sering adalah notif gagal login atau PAM auth failure (vscode-bin aur, github-desktop.deb from github source)

1. Add the following line to /etc/pam.d/login (I guess the leading dash is important):
```cfg
auth      optional     pam_gnome_keyring.so
session    optional     pam_gnome_keyring.so        auto_start
```

2. Add the following line to /etc/pam.d/passwd:
```cfg
password      optional        pam_gnome_keyring.so
```

3. Add these lines to ~/.xinitrc:
```cfg
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
```

Sumber : 

- [https://github.com/MicrosoftDocs/live-share/issues/213#issuecomment-383326750](https://github.com/MicrosoftDocs/live-share/issues/213#issuecomment-383326750)
- [https://wiki.archlinux.org/title/GNOME/Keyring#PAM_method](https://wiki.archlinux.org/title/GNOME/Keyring#PAM_method)

**Comment by owl4ce** [comment]
Why opened multiple issues?

**Comment by owl4ce** [comment]
I think this is just an additional, moving to the discussion. **Why?** I didn't experience this.
