### ISSUE TITLE
Installation on Ubuntu 

### ISSUE THREAD

**Issue by imskr** [owl4ce/dotfiles#13]
- I setup this workflow by following readme.
- However I'm getting some errors, also how to enable touch to click on it?

![2020-10-14-121848_1920x1080_scrot](https://user-images.githubusercontent.com/42062622/95954352-c9a57580-0e18-11eb-892d-31fc65ef913e.png)

**Comment by beppevoto** [comment]
To fix this error write "sudo apt install python2" in your terminal (without quotes) @imskr

**Comment by imskr** [comment]
@beppevoto I fixed it. But i checked system settings click on tap is ON but still its not working only buttons click is working not the touchpad

**Comment by owl4ce** [comment]
To be honest, I've never tried to install it on a debian-based distro. Sorry.

**Comment by owl4ce** [comment]
@lmskr 
If the problem is only in the menu for monitor settings with python2, you can turn it off on
![2020-10-15-055649_1080x34_scrot-framed](https://user-images.githubusercontent.com/53987136/96054172-41bc7b80-0eab-11eb-8248-8846736f887a.png)
_~/.config/obmenu-generator/schema.pl_

**Comment by fairuzmn** [comment]
I got same problem in my Ubuntu 20.04

this happens because python2 is not installed on your system
Try to install Python2

`sudo apt install python`

after i install python with that command, this problem is gone and i can change my screen resolution
