### ISSUE TITLE
Zsh prompt visual glitching? [Bug]

### ISSUE THREAD

**Issue by neptalactone** [owl4ce/dotfiles#131]
Hi, whenever i open termite or any other terminal. I've experienced this weird glitch that makes it overwrite previous syntax or make random spacing.

I assume the prompt should not be overwrite. but every time i enter a command, it will will overwrite the prefix prompt, and if i type long command it will also overwrite the suffix prompt. moreover, sometimes when i typing and/or tabbing (to use zsh completion) it sometimes overwrite the previous syntax/command. 

Here a few screenshot of it happening.

![Problem 1](https://user-images.githubusercontent.com/34985816/129446449-5eed4609-3395-480b-b6a7-d393863c0a03.png)
Fig.1

![Problem 2](https://user-images.githubusercontent.com/34985816/129446456-53318ab6-39f2-4378-a910-b7862b546c12.png)
Fig. 2

I use your setup on my laptop running Arch Linux with xanmod kernel. I didn't add anything to the configuration except adding pipewire.service to run at startup.

Any thoughts?

**Comment by owl4ce** [comment]
I think it's locale issues. Try this in your terminal.
```sh
echo $LANG $LC_ALL
```

Let me know 🤔

**Comment by owl4ce** [comment]
> I think it's locale issues. Try this in your terminal.

It should use **UTF-8**.

**Comment by neptalactone** [comment]
Oh and also, i was wondering why the prompt didn't display correctly if i'm using rxvt?

It display like this. and the glitch still there.
![2021-08-14-193533_765x392_scrot](https://user-images.githubusercontent.com/34985816/129446548-5ea8fd68-f0df-46a0-8b05-89ae774e9a0c.png)
Fig. 1 

![2021-08-14-193745_769x394_scrot](https://user-images.githubusercontent.com/34985816/129446582-2393d247-8dc8-4534-8f62-7a03d6c5cb3c.png)
Fig.2

it's said i use C locale. that's weird. I change it to en_US.UTF-8. 

EDIT: Looks like i forgot to set LANG variable on /etc/locale.conf when i install arch.

**Comment by owl4ce** [comment]
Anyway, to use **framed screenshot** you just need to click on the window without moving the cursor (selection). So that would be perfect.

**Comment by owl4ce** [comment]
> it's said i use C locale. that's weird. I change it to en_US.UTF-8.

Don't use C locale, set it to UTF-8. You may forgot that. 😄

**Comment by owl4ce** [comment]
<p align="center"><img src="https://user-images.githubusercontent.com/53987136/129446711-34403027-fcc5-44e6-a586-1f61bdd931a7.png"/></p>

**Comment by neptalactone** [comment]
Yeah, i forgot to set it on /etc/locale.conf file when i install arch. Thanks. I never knew that was the cause

**Comment by owl4ce** [comment]
I'll probably add this (about locale) to README.md, so peoples won't forget.
