### ISSUE TITLE
Network interface not found [Bug]

### ISSUE THREAD

**Issue by br4inbre4k** [owl4ce/dotfiles#147]
Bug with the tint2 panel on either themes. I tried finding the script but I don't know where its located so I can't change the interface it uses. 
![2021-09-17_20-10](https://user-images.githubusercontent.com/88006795/133841298-893fce18-487d-4b7b-9325-278435f40b34.png)
This is on the newest build of Artix and all the recommended packages.

**Comment by Kraautokratt** [comment]
Artix may have meddled with the wifi interface. It could be "wlan0", you could check it with iwconfig.

On the other hand, the script is located in ~/.owl4ce_var (from line 85-86)

     INT_ETH="enp1s0"
     INT_WIFI="wlp1s0"
     TEMP_DEV="thermal_zone0"

**Comment by owl4ce** [comment]
> Bug with the tint2 panel on either themes. I tried finding the script but I don't know where its located so I can't change the interface it uses.
> ![2021-09-17_20-10](https://user-images.githubusercontent.com/88006795/133841298-893fce18-487d-4b7b-9325-278435f40b34.png)
> This is on the newest build of Artix and all the recommended packages.

Answered by @Kraautokratt. TBH, I use `wlan0` and `eth0` in my setup like Artix Linux does.
