### ISSUE TITLE
Old panels not closing on theme change / mode change

### ISSUE THREAD

**Issue by SamHep0803** [owl4ce/dotfiles#15]
Hi!

Just wanted to start of by saying this is absolutely beautiful and thanks very much for making it. However I am having a few issues with it right now, when I change the theme from Mechanical to Eyecandy (or vice versa) or if I change the Visual Mode to minimal or not, the old tint2 panels don't close, creating this weird theme mash which doesn't really look all too pleasing. The only way i can get the panels to go away is by restarting open box completely.

I'm running this on Debian 10 and I start openbox by using `startx` if that helps at all. 

I would appreciate the help very much as I really like these dotfiles :)

**Comment by owl4ce** [comment]
**Thanks!**  
Make sure that the command `killall tint2` is working properly to close tint2, you can try it in the terminal.  
Also make sure there is a command in this file:

![2020-10-18-111332_468x247_scrot-framed](https://user-images.githubusercontent.com/53987136/96358597-28c5fb80-1133-11eb-814e-407a4475decd.png)
_~/.config/openbox/visual-mode/kill-ui_

![2020-10-18-111424_496x91_scrot-framed](https://user-images.githubusercontent.com/53987136/96358593-2663a180-1133-11eb-82f7-4eb55d2c99a1.png)
_~/.config/openbox/visual-mode/switcher_

**Comment by SamHep0803** [comment]
Hey thanks for replying, turns out I didn't have `psmisc` installed, which contains the killall command haha. One last thing, when I change themes, URxvt doesn't change it's color, the bar at the top with the exit buttons etc that changes to dark or to light but the actual terminal is stuck at being white all the time. What could be the reason for that?

**Comment by owl4ce** [comment]
URxvt does not automatically change color when the theme changes, it must be adjusted yourself. Because the light theme attracts bug haha.

**Comment by owl4ce** [comment]
If a problem occurs, reverse the sign! in _.Xresources_ below. Because I just reversed it with the `sed` command in the _~/.scripts/reverse-urxvt-bw_.

![2020-10-18-182326_333x327_scrot-framed](https://user-images.githubusercontent.com/53987136/96366012-11a4ff00-116f-11eb-89ee-39a4b008e55b.png)

**Comment by SamHep0803** [comment]
Thanks very much! Well done on making this, it's really really good.
