### ISSUE TITLE
Deprecated Dunst syntax [Bug]

### ISSUE THREAD

**Issue by akinokonomi** [owl4ce/dotfiles#156]
**Describe the bug**
There were some deprecations in Dunst awhile ago, but I see you still use deprecated settings, one of which certainly is:

https://github.com/owl4ce/dotfiles/blob/af8e68120ef89e3724a33f45e6f8ecc0580bf4c0/.config/dunst/dunstrc-eyecandy#L6

```
 $ man dunst.5 | less +/geometry
...
       geometry DEPRECATED
           This setting is deprecated. It's split up into width, height, origin, notification_limit and
           offset.
...
```

Look [their changelog](https://github.com/dunst-project/dunst/blob/master/CHANGELOG.md#170----2021-10-19).

**Expected behavior**
To keep config files up to date. 

Not always possible, of course.

**Screenshots**
<details><summary>(None)</summary>

（ノ♯｀△´）ノ~┻━┻

┬─┬ ノ( ^_^ノ)

(ノಠ益ಠ)ノ彡┻━┻

(x _ x)☆┻━┻~~~＼（≧ロ≦＼）

</details>

**Desktop (please complete the following information):**
 - **OS**: Arch Linux

**Additional context**
```
 $ dunst -v    
Dunst - A customizable and lightweight notification-daemon 1.7.0 (2021-10-19)
```

**Comment by owl4ce** [comment]
Thank you @akinokonomi,

I'll update to the  version. Currently the `dunst` on Gentoo still uses version 1.6.1.

**Comment by owl4ce** [comment]
According to the new version of dunst, we can get a rid `notify-send.sh` from dependencies. Use `dunstify`.

**Comment by akinokonomi** [comment]
I've heard about dunstify, though never used.
Will be glad to see the translation to it, if it's really so good now.
