### ISSUE TITLE
Capture context menu on screenshot [Feature Req]

### ISSUE THREAD

**Issue by FlyingCat-X** [owl4ce/dotfiles#157]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to take screenshots with the context menu open but every time I try to do it, the context menu closes and doesn't appear in the screenshot

**Describe the solution you'd like**
Take the screenshot with the context menu open and don't close it when doing so

**Describe alternatives you've considered**
idk if this is related but i have a similar problem in fullscreen games, but only when I try to take a screenshot of a portion of the screen, I have attached a video in additional context testing both

**Additional context**

https://user-images.githubusercontent.com/33896771/139604160-8bd3eb62-ad8f-4839-9b18-66aff5a4a6b7.mp4

**Comment by owl4ce** [comment]
Sadly, I still don't know how to invoke WM's keybind when context menu appear.

**Comment by FlyingCat-X** [comment]
I think timer mode works for me as a workaround for now. Thank you ^^

**Comment by akinokonomi** [comment]
Oh. That was bothering me, too.
Though not so much as to begin searching/thinking of the solution.

Thank you, @owl4ce!
