### ISSUE TITLE
How to uninstall your dots

### ISSUE THREAD

**Issue by sheeepdev** [owl4ce/dotfiles#158]
Hey, sorry but I decided I wanna switch to GNOME/KDE (Haven't decided yet) and I currently have your dots installed, how can I remove everything so I can install Gnome/KDE? Thanks

**Comment by akinokonomi** [comment]
You better create a new user for each: KDE, GNOME, etc. Especially if you haven't decided yet.

**Comment by sheeepdev** [comment]
> You better create a new user for each: KDE, GNOME, etc. Especially if you haven't decided yet.

I decided to install GNOME and its working, but now I need to remove openbox and all openbox-related configs

**Comment by akinokonomi** [comment]
> but now I need to remove openbox 

What distribution do you use?

> and all openbox-related configs

This is one of the reasons why you should have created a new user.

**Comment by sheeepdev** [comment]
> > but now I need to remove openbox
> 
> What distribution do you use?
> 
> > and all openbox-related configs
> 
> This is one of the reasons why you should have created a new user.

I already have ALL my projects, scripts and other things scattered around my home directory (my user) and I can't afford to just make another user

I use Arch Linux.

**Comment by lymau** [comment]
I want to remove the dotfiles too. I'm used to GNOME after all.

**Comment by sheeepdev** [comment]
> I want to remove the dotfiles too. I'm used to GNOME after all.

Same

**Comment by owl4ce** [comment]
Sorry guys, I've been busy lately.

It's actually simple, but it's not as it seems especially for package dependencies.

In simple terms, create a new user which already answered by @akinokonomi. Or try hard when you understand all of this setup, manually delete all the files in the user's home directory according to the ones in the dotfiles repo then delete the dependencies excluding  pulseaudio and X11 things, adjust by yourself.

I'm currently setting up the 4th version, where my main goals are directory cleanliness, portability, and ease of installation. So that in the next version, I hope to make a list of files which will be easily deleted without disturbing other DEs.

Issues closed, but Q&A will be responded slowly. Thanks.

**Comment by owl4ce** [comment]
I'm late to tell :)

> ## Installation (dependencies)
> > Customize your choice about dependencies below, this is my complete setup as I use Gentoo/Linux with single OpenboxWM and my preference utility softwares. So, what's in the column is the minimal setup from base-distro installation, everything should be fine without confused screaming, do with your own risk.

> ### Detailed environment
> Please refer to [wiki/Detailed-Environment](https://github.com/owl4ce/dotfiles/wiki/Detailed-Environment).

**Comment by akinokonomi** [comment]
> but now I need to remove openbox

> I use Arch Linux.

@sheeepdev, Then the best you can do for now, having no understanding of meaning of those packages, is 
to copy the _current_ [list of dependencies]( https://github.com/owl4ce/dotfiles#installation-dependencies) and wait for the time when you _will_ understand what they are for.

But I guess you can remove:
`openbox` `picom-git` `ncmpcpp` `mpc` `mpv` `parcellite` `viewnior` `tint2` `nitrogen` `dunst` `scrot` 
`rxvt-unicode-truecolor-wide-glyphs` `lxsession` 
without any harm to your GNOME. (Do it at your own risk.)

> I already have ALL my projects, scripts and other things scattered around my home directory (my user) and I can't afford to just make another user

Too bad, but creating new user is always for the best. I only can advice you to sort them out and keep them tidy.

**Comment by sheeepdev** [comment]
> > but now I need to remove openbox
> 
> > I use Arch Linux.
> 
> @sheeepdev, Then the best you can do for now, having no understanding of meaning of those packages, is to copy the _current_ [list of dependencies](https://github.com/owl4ce/dotfiles#installation-dependencies) and wait for the time when you _will_ understand what they are for.
> 
> But I guess you can remove: `openbox` `picom-git` `ncmpcpp` `mpc` `mpv` `parcellite` `viewnior` `tint2` `nitrogen` `dunst` `scrot` `rxvt-unicode-truecolor-wide-glyphs` `lxsession` without any harm to your GNOME. (Do it at your own risk.)
> 
> > I already have ALL my projects, scripts and other things scattered around my home directory (my user) and I can't afford to just make another user
> 
> Too bad, but creating new user is always for the best. I only can advice you to sort them out and keep them tidy.

I understand, and I have tidied them put as much as I can but its still not ready for everything to move to another user.
