### ISSUE TITLE
Border's colors [Bug]

### ISSUE THREAD

**Issue by geotraumaticxp** [owl4ce/dotfiles#159]
**Describe the bug**
I don't know is it a bug or not, but it seems to be. So, the problem is with openbox menu - the outer border line is not the same color as the background, and I see that on screenshots of default setup they should be same. What is more, when I select an option from menu, for example "Launch apps", the right border of menu turns black or dark-grey, blinks for a few seconds, and then returns to "normal" color.

**Expected behavior**
I suppose colors of menu should be as on screenshots in gallery. 

**Screenshots**
+ 

**Desktop (please complete the following information):**
 - **OS**: Arch Linux 

**Additional context**
I also want to ask, is this right that on Minimal Mode (which is where different indicators such as volume, date, network and they are on the top panel by default) there are only one tab can be active on panel? For example, I can run many applications in the same time, but only one of them will appear on taskbar (My file manager or browser, for example). In the Visual Mode I can just launch the needed applications from that "circles" on panel and not use alt + tab to switch between opened windows. 

P. S. Nevertheless, thanks for making such a beautiful desktop. I'm also sorry, if I wrote this in the wrong section and issues like this are supposed to be in discussions and the things are as they should be.

![blackborders](https://user-images.githubusercontent.com/94459622/141997990-2234195e-2d2c-4809-9f81-4ddeb3328538.png)
![Differentborders](https://user-images.githubusercontent.com/94459622/141997994-f9e43f57-1bbc-4bba-9385-32d17e965444.png)

**Comment by alizteralvord** [comment]
https://github.com/owl4ce/dotfiles#installation-dependencies : Attention section!
> - I guess the latest [`yshui/picom`](https://github.com/yshui/picom/issues) might be problematic on certain devices. On me, experiencing some border flickering on the Openbox desktop menu (right click). So I [checkout](https://devopscube.com/checkout-clone-specific-git-commit-id-sha) it on commit **[9cb552e](https://github.com/yshui/picom/commit/9cb552ecd91ec644bf6fcb558ddd44fda5b4f7d9)**.

**Comment by geotraumaticxp** [comment]
Thanks a lot, It's working right now.

**Comment by geotraumaticxp** [comment]
Wait, I'm sorry. I just used another way to solve this problem (through `killall picom`) but it deleted rounded corners of windows. 

When I'm trying to do as it was said, on the stage 

> after that you rebuild the picom again

I received this: `==> ERROR: PKGBUILD does not exist.` (I use` makepkg -si` command)

How can I fix that?

**Comment by alizteralvord** [comment]
> Wait, I'm sorry. I just used another way to solve this problem (through `killall picom`) but it deleted rounded corners of windows.
> 
> When I'm trying to do as it was said, on the stage
> 
> > after that you rebuild the picom again
> 
> I received this: `==> ERROR: PKGBUILD does not exist.` (I use` makepkg -si` command)
> 
> How can I fix that?

make sure you have all the Dependencies needed
- clone picom and checkout to 9cb552e
    `git clone https://github.com/yshui/picom.git`
    `cd picom`
    `git checkout 9cb552e`
- build
    `git submodule update --init --recursive`
    `meson --buildtype=release . build`
    `ninja -C build`
- install
    `ninja -C build install`


for more details [README.md](https://github.com/yshui/picom#readme)

**Comment by geotraumaticxp** [comment]
Hm...what distro are you using? Because when I'm trying to build with ninja `ninja -C build`, it's written:

```
ninja: Entering directory 'build'
ninja: error: loading 'build.ninja': No such file or directory
```

**Comment by owl4ce** [comment]
> I also want to ask, is this right that on Minimal Mode (which is where different indicators such as volume, date, network and they are on the top panel by default) there are only one tab can be active on panel? For example, I can run many applications in the same time, but only one of them will appear on taskbar (My file manager or browser, for example). In the Visual Mode I can just launch the needed applications from that "circles" on panel and not use alt + tab to switch between opened windows.

Yes, all in my screenshot (v3.2) it's normal.

**Comment by owl4ce** [comment]
Just found out using `--experimental-backends` can fix this issue using latest picom-git. Also `dual_kawase` blur works like a charm with rounded corners enabled.
