### ISSUE TITLE
Unable to take a screenshot with shot-seldraw [Bug]

### ISSUE THREAD

**Issue by FlyingCat-X** [owl4ce/dotfiles#160]
**Describe the bug**
When I try to take a screenshot of a region of the screen I get a `Screenshot canceled` message.

**Expected behavior**
That the screenshot is captured correctly after selecting the desired region.

**Screenshots**
![image](https://user-images.githubusercontent.com/33896771/143372656-465772b7-5a92-40f4-8b77-3a324001ce95.png)

**Desktop (please complete the following information):**
 - **OS**: Arch Linux

**Additional context**
I get these errors when I try to execute these commands in the terminal.
![image](https://user-images.githubusercontent.com/33896771/143373167-5ee563da-5fdf-4368-81c3-e1c78fdf1479.png)

**Comment by alizteralvord** [comment]
I downgrade to version `1.6`

**Comment by stay127** [comment]
do downgrade to previous versi will do trick, btw what szh u use? cause my zsh or urxvt is only that pink arrow not with that "main" option

**Comment by FlyingCat-X** [comment]
Downgrading did the trick. Thank you :3 
@stay127 I use the theme that came with the dotfiles (ar-round). Take a look at `$HOME/.oh-my-zsh/custom/themes/ar-round.zsh-theme` to see if it looks like this:
https://github.com/owl4ce/dotfiles/blob/af8e68120ef89e3724a33f45e6f8ecc0580bf4c0/.oh-my-zsh/custom/themes/ar-round.zsh-theme#L22
The `$(git_prompt_info)` part seems to be the one that adds `main` in the terminal

**Comment by owl4ce** [comment]
**Hi @FlyingCat-X** 

Change this
https://github.com/owl4ce/dotfiles/blob/af8e68120ef89e3724a33f45e6f8ecc0580bf4c0/.scripts/shot-seldraw#L10

into this
```sh
10    if scrot -q 75 -s -f -b -e 'mv -f $f /tmp/' -l style=dash,width=3,color='#2be491'; then 
```

Issue closed, thanks.
