### ISSUE TITLE
Laptop Manual Lock

### ISSUE THREAD

**Issue by Nxwxz** [owl4ce/dotfiles#161]
**Describe the bug**
After manually locking the screen, xautolock would lock again after the timer set in .owl4ce_var. This caused a frozen lock screen after entering password to unlock again. The system was still running as I can use the keybinds to open up terminal and pkill slimlock. It seems that pressing the lock key on my laptop runs slimlock by itself, then xautolock runs it aswel after the set timer causing two instances of the lockscreen. Also, when returning from suspend the screensaver shows what was on my screen before locking leaking what information, then when I move my cursor it shows the lock screen.

**Expected behavior**
Xautolock should not lockscreen again if the screen has already been manually locked. Screensaver should not show users desktop.

**Screenshots**

**Desktop (please complete the following information):**
Arch Linux

**Additional context**
I was able to fix this by keybindnig the lock button in the openbox rc.xml to "bash -c "xautolock -locknow"" it was previously set to slimlock. This fixes the dual lock screen but it seems a little glitchy when locking now. It will flicke between mydesktop and the lockscreen before locking at times.

**Comment by owl4ce** [comment]
**Hi @Nxwxz** 

Thanks for reporting the issue. The next version probably moving to [`xss-lock`](https://wiki.archlinux.org/title/Session_lock#xss-lock) due to have better "trigger".

**Comment by owl4ce** [comment]
<span>Fun fact right now I don't use any lockacreen BTW.</span>

**Comment by Nxwxz** [comment]
> Fun fact right now I don't use any lockscreen BTW.

Ouu nice, no lockscreen on laptop aswell? I only have a laptop and I don't think I could use it without a lockscreen lmao

**Comment by owl4ce** [comment]
> > Fun fact right now 
> Ouu nice, no lockscreen on laptop aswell? I only have a laptop and I don't think I could use it without a lockscreen lmao

Yeah, I would like to use `xtrlock` to lock input. Looking for better `xtrlock` fork/improvements.

**Comment by owl4ce** [comment]
Switched to `xss-lock`. Thanks.

https://github.com/owl4ce/dotfiles/blob/4760330732ac760c17bf474e194827506fc5f030/.config/openbox/autostart.sh#L32-L35

https://github.com/owl4ce/dotfiles/blob/4760330732ac760c17bf474e194827506fc5f030/.config/openbox/joyful-desktop/xss-lock-tsl.sh#L1-L31
