### ISSUE TITLE
Rofi menu theme is messed up

### ISSUE THREAD

**Issue by legendaryzyper** [owl4ce/dotfiles#162]
**Describe the bug**
The menus of rofi (sound, power, music, ...) got the theme messed up.

**Expected behavior**
They should look exactly like in the screenshots and video showcase.

**Screenshots**

![2021-12-05-131624_1920x1080_scrot](https://user-images.githubusercontent.com/88670305/144736364-f5c52692-bece-44e9-8aa6-07da9e26228d.png)

![2021-12-05-131743_1920x1080_scrot](https://user-images.githubusercontent.com/88670305/144736401-5486b816-8f49-431d-85cb-6b4bf7270347.png)
**Desktop (please complete the following information):**
 - **OS**: Arch Linux

**Additional context**
My rofi version is 1.7.2.

**Comment by legendaryzyper** [comment]
Downgrading rofi fixed the issue so it's rofi's fault. You can close now ^^

**Comment by legendaryzyper** [comment]
Downgrading rofi fixed the issue.

**Comment by owl4ce** [comment]
> Downgrading rofi fixed the issue.

Yeah, sorry for now this dotfiles in deperecate state for a while. Majority caused by rofi, etc. Currently working for the next version.
