### ISSUE TITLE
Audio-volume changer not working [Bug]

### ISSUE THREAD

**Issue by Endeavour821** [owl4ce/dotfiles#163]
i cant control my volume with my keyboard , but the audio is working

OS : lubuntu 20.04

when im directly using amixer in terminal , its working, but when im try to execute  script bash c '~/.scripts/notify/change-volume down' it will error , thankyou :)
![2021-12-16-190828_1366x768_scrot](https://user-images.githubusercontent.com/71737156/146370186-4fa293d4-8142-4e7e-b422-3c1e21b7c2d0.png)

![2021-12-16-190649_1366x768_scrot](https://user-images.githubusercontent.com/71737156/146370140-781aa389-2d9d-481d-befd-607276eb55b9.png)

**Comment by owl4ce** [comment]
The problem is alsa device, can you check available device?
```sh
amixer
```

**Comment by owl4ce** [comment]
> The problem is alsa device, can you check available device?
> 
> ```shell
> amixer
> ```

NVM, seems caused by grep pipe or something. :thinking:


Try debug,
```sh
bash -cx /path/script
```

**Comment by Endeavour821** [comment]
solved by rolling back scripts with version 2.0
idk why this happen, is bcause my amixer version is 1.2.2 ?
but thanks for the response ~
![2021-12-17-081959_1366x768_scrot](https://user-images.githubusercontent.com/71737156/146473219-ba0cac0b-a78f-4e9a-885c-c4e88b785189.png)
