### ISSUE TITLE
I can't open terminal and change wallpaper

### ISSUE THREAD

**Issue by Kalserl** [owl4ce/dotfiles#165]
As title, I can't open terminal and change wallpaper.
I tried to right click -> Terminal and it did't work, I tried to wallpaper by using button wallpaper in taskbar, it didn't work too.
I using archcraft os and using xfce terminal
Do you have any solution ?

**Comment by owl4ce** [comment]
> Do you have any solution ?

Can you debug the shell-script (bash) and share the outputs here?
```sh
$ # Wallpaper changer.
$ bash -x ~/.config/openbox/visual-mode/wally
$ # Launcher.
$ bash -x ~/.scripts/default-apps/launch file_manae
```

<span>I don't really know what happen here, there are many context about shell-script issues happened when trying my dots these days.</span>

So, as in this GitHUb repo description, I deprecate the newest version of my dotfiles and working for the next version v4 with cleanest setup. Wait until next month, hopefully finished.

**Comment by Kalserl** [comment]
I run 2 shell script and it's my outputs (With the first i succeed to change wallpaper)


bash -x ~/.config/openbox/visual-mode/wally
--- Select wallpaper for Eyecandy Theme
+ for image in "$WALL_DIR"/*.*
+ N=1
++ grep -oE '[^/]+$'
+ printf '\e[1;35m[\e[0m1\e[1;35m] \e[0;31m61531cd01a39e_4K.jpg\n'
[1] 61531cd01a39e_4K.jpg
+ eval 'image1=$image'
++ image1=/home/evergarden/.wallpaper/eyecandy/61531cd01a39e_4K.jpg
+ for image in "$WALL_DIR"/*.*
+ N=2
++ grep -oE '[^/]+$'
+ printf '\e[1;35m[\e[0m2\e[1;35m] \e[0;31mcherry-blossoms_FHD.jpg\n'
[2] cherry-blossoms_FHD.jpg
+ eval 'image2=$image'
++ image2=/home/evergarden/.wallpaper/eyecandy/cherry-blossoms_FHD.jpg
+ for image in "$WALL_DIR"/*.*
+ N=3
++ grep -oE '[^/]+$'
+ printf '\e[1;35m[\e[0m3\e[1;35m] \e[0;31mfloral-artistic-1_FHD.jpg\n'
[3] floral-artistic-1_FHD.jpg
+ eval 'image3=$image'
++ image3=/home/evergarden/.wallpaper/eyecandy/floral-artistic-1_FHD.jpg
+ for image in "$WALL_DIR"/*.*
+ N=4
++ grep -oE '[^/]+$'
+ printf '\e[1;35m[\e[0m4\e[1;35m] \e[0;31mfloral-artistic-2_FHD.jpg\n'
[4] floral-artistic-2_FHD.jpg
+ eval 'image4=$image'
++ image4=/home/evergarden/.wallpaper/eyecandy/floral-artistic-2_FHD.jpg
+ for image in "$WALL_DIR"/*.*
+ N=5
++ grep -oE '[^/]+$'
+ printf '\e[1;35m[\e[0m5\e[1;35m] \e[0;31mmountain-1_HD.jpg\n'
[5] mountain-1_HD.jpg
+ eval 'image5=$image'
++ image5=/home/evergarden/.wallpaper/eyecandy/mountain-1_HD.jpg
+ for image in "$WALL_DIR"/*.*
+ N=6
++ grep -oE '[^/]+$'
+ printf '\e[1;35m[\e[0m6\e[1;35m] \e[0;31mmountain-2_3K.jpg\n'
[6] mountain-2_3K.jpg
+ eval 'image6=$image'
++ image6=/home/evergarden/.wallpaper/eyecandy/mountain-2_3K.jpg
+ for image in "$WALL_DIR"/*.*
+ N=7
++ grep -oE '[^/]+$'
+ printf '\e[1;35m[\e[0m7\e[1;35m] \e[0;31mmountain-3_8K.jpg\n'
[7] mountain-3_8K.jpg
+ eval 'image7=$image'
++ image7=/home/evergarden/.wallpaper/eyecandy/mountain-3_8K.jpg
+ for image in "$WALL_DIR"/*.*
+ N=8
++ grep -oE '[^/]+$'
+ printf '\e[1;35m[\e[0m8\e[1;35m] \e[0;31mmountain-4_3K.jpg\n'
[8] mountain-4_3K.jpg
+ eval 'image8=$image'
++ image8=/home/evergarden/.wallpaper/eyecandy/mountain-4_3K.jpg
+ for image in "$WALL_DIR"/*.*
+ N=9
++ grep -oE '[^/]+$'
+ printf '\e[1;35m[\e[0m9\e[1;35m] \e[0;31msnow_FHD.jpg\n'
[9] snow_FHD.jpg
+ eval 'image9=$image'
++ image9=/home/evergarden/.wallpaper/eyecandy/snow_FHD.jpg
+ printf '\e[1;36m-\e[5;32m-\e[0m\e[1;36m- \e[1;37mEnter File Index ID \e[1;35m[\e[0m1-9\e[1;35m]\e[1;37m: \e[0m'
--- Enter File Index ID [1-9]: + read -r NUM
1
++ tr -dc '[:digit:]'
+ NUM=1
+ [[ 1 -eq 0 ]]
+ [[ 1 -gt 9 ]]
+ eval 'IMG=$image1'
++ IMG=/home/evergarden/.wallpaper/eyecandy/61531cd01a39e_4K.jpg
+ nitrogen --set-zoom-fill --save /home/evergarden/.wallpaper/eyecandy/61531cd01a39e_4K.jpg
++ grep -oE '[^/]+$'
+ SELECTED=61531cd01a39e_4K.jpg
+ echo 61531cd01a39e_4K.jpg
++ '[' -n '' ']'
++ echo /home/evergarden/.config/openbox/visual-mode/eyecandy/wall.joy
+ printf '\e[1;36m[\e[5;32m√\e[0m\e[1;36m] \e[1;37mSelected wallpaper: \e[0;31m61531cd01a39e_4K.jpg\n'
[√] Selected wallpaper: 61531cd01a39e_4K.jpg
+ /home/evergarden/.scripts/notify/notify-send.sh -u low -r 99 -i /home/evergarden/.icons/gladient/wally.png $'\357\237\253' '<span size='\''small'\''><u>61531cd01a39e_4K.jpg</u></span>\nSuccessfully applied'
+ exit 0
                                                                          ~  





bash -x ~/.scripts/default-apps/launch filemanager                      ~  
+ . /home/evergarden/.owl4ce_var
++ OB_DIR=/home/evergarden/.config/openbox
++ THEME_DIR=/home/evergarden/.themes
++ VISMOD_DIR=/home/evergarden/.config/openbox/visual-mode
++ TINT2_DIR=/home/evergarden/.config/tint2
++ ROFI_DIR=/home/evergarden/.config/rofi
++ ROFI_SIDEBAR_DIR=/home/evergarden/.config/rofi/themes/sidebar
++ ROFI_COLORSCHEMES_DIR=/home/evergarden/.config/rofi/themes/shared/colorschemes
++ DUNST_DIR=/home/evergarden/.config/dunst
++ ICON_GLADIENT_DIR=/home/evergarden/.icons/gladient
++ OB_BUTTON_DIR=/home/evergarden/.themes/Buttons
++ SCRIPTS_DIR=/home/evergarden/.scripts
++ NOTIFY_DIR=/home/evergarden/.scripts/notify
++ STATE_EXT=joy
++ MPD_DIR=/home/evergarden/.mpd
++ NCMPCPP_DIR=/home/evergarden/.ncmpcpp
++ NCMPCPP_SCRIPTS_DIR=/home/evergarden/.ncmpcpp/scripts
++ MPD_CONFIG=/home/evergarden/.mpd/mpd.conf
++ MPD_CURRENT_TRACK=/home/evergarden/.ncmpcpp/scripts/current-track.joy
++ NCMPCPP_COVER=/tmp/cover.jpg
++ NCMPCPP_NOTIF_COVER=/tmp/cover-notify.jpg
+++ grep -oP 'music_directory.*"\K[^"]+' /home/evergarden/.mpd/mpd.conf
++ GET_MPD_MUSIC_DIR='/run/media/evergarden/New Volume/Entertain/Music/Music List/'
+++ sh -c 'echo /run/media/evergarden/New Volume/Entertain/Music/Music List/'
++ CHK_MPD_MUSIC_DIR='/run/media/evergarden/New Volume/Entertain/Music/Music List/'
++ OB_CONFIG=/home/evergarden/.config/openbox/rc.xml
++ GTK2_CONFIG=/home/evergarden/.gtkrc-2.0
++ GTK3_CONFIG=/home/evergarden/.config/gtk-3.0/settings.ini
++ XSETTINGSD_CONFIG=/home/evergarden/.xsettingsd
++ ROFI_FULLSCREEN_CONFIG=/home/evergarden/.config/rofi/themes/shared/settings.rasi
++ ROFI_SIDEBAR_CONFIG=/home/evergarden/.config/rofi/themes/sidebar/colors.rasi
++ XRESOURCES_CONFIG=/home/evergarden/.Xresources
++ TERMITE_CONFIG=/home/evergarden/.config/termite/config
++ OB_TRAY=/home/evergarden/.config/openbox/tray
++ MOD_FILE=/home/evergarden/.config/openbox/visual-mode/current.joy
++ ORT_FILE=/home/evergarden/.config/openbox/visual-mode/orientation.joy
++ DEFAPPS_FILE=/home/evergarden/.scripts/default-apps/list.joy
+++ grep -oP '.*[^ &]+' /home/evergarden/.config/openbox/tray
+++ grep -Fv '#'
++ CHK_TRAY=parcellite
+++ grep -oE 'mechanical|eyecandy' /home/evergarden/.config/openbox/visual-mode/current.joy
++ CHK_VISMOD=eyecandy
+++ grep -Fo minimal /home/evergarden/.config/openbox/visual-mode/current.joy
++ CHK_MINMOD=
+++ grep -oP 'state="\K[^"]+' /home/evergarden/.config/openbox/visual-mode/orientation.joy
++ CHK_ORT=vertical
+++ grep -oP 'vertical="\K[^"]+' /home/evergarden/.config/openbox/visual-mode/orientation.joy
++ CHK_ORT_V=left
+++ grep -oP 'horizontal="\K[^"]+' /home/evergarden/.config/openbox/visual-mode/orientation.joy
++ CHK_ORT_H=bottom
+++ grep -o '<titleLayout>.*</titleLayout>' /home/evergarden/.config/openbox/rc.xml
++ CHK_OB_BUTTON_LOC='<titleLayout>LIMC</titleLayout>'
++ WALL_RAW_SOURCE=/home/evergarden/.wallpaper
++ WALL_DIR=/home/evergarden/.wallpaper/eyecandy
++ VISMOD_WALL_FILE=/home/evergarden/.config/openbox/visual-mode/eyecandy/wall.joy
++ MINMOD_WALL_FILE=/home/evergarden/.config/openbox/visual-mode/eyecandy/wall-minimal.joy
++ VISMOD_BUTTON_FILE=/home/evergarden/.config/openbox/visual-mode/eyecandy/button.joy
++ MINMOD_BUTTON_FILE=/home/evergarden/.config/openbox/visual-mode/eyecandy/button-minimal.joy
++ VISMOD_LOC_BUTTON_FILE=/home/evergarden/.config/openbox/visual-mode/eyecandy/bloc.joy
++ MINMOD_LOC_BUTTON_FILE=/home/evergarden/.config/openbox/visual-mode/eyecandy/bloc-minimal.joy
++ VISMOD_ROFI_FILE=/home/evergarden/.config/openbox/visual-mode/eyecandy/rofi
++ VISMOD_DUNST_FILE=/home/evergarden/.config/openbox/visual-mode/eyecandy/dunst
++ CHK_VISMOD_WALL=61531cd01a39e_4K.jpg
++ CHK_MINMOD_WALL=floral-artistic-2_FHD.jpg
++ CHK_VISMOD_BUTTON=Lovely
++ CHK_MINMOD_BUTTON=Dots2
++ CHK_VISMOD_LOC_BUTTON=right
++ CHK_MINMOD_LOC_BUTTON=right
+++ '[' -n '' ']'
+++ echo /home/evergarden/.config/openbox/visual-mode/eyecandy/rofi.joy
++ CURRENT_ROFI_MOD=/home/evergarden/.config/openbox/visual-mode/eyecandy/rofi.joy
++ CHK_ROFI_MOD=vertical
+++ '[' -n '' ']'
+++ echo /home/evergarden/.config/openbox/visual-mode/eyecandy/dunst.joy
++ CURRENT_DUNST_MOD=/home/evergarden/.config/openbox/visual-mode/eyecandy/dunst.joy
++ CHK_DUNST_MOD=dunstrc-eyecandy
++ MECH_BUTTON_DIR=/home/evergarden/.themes/Fleon/openbox-3
++ EYC_BUTTON_DIR=/home/evergarden/.themes/Sweetly/openbox-3
++ NOTIF_MECH_ICON=/home/evergarden/.icons/gladient/mech.png
++ NOTIF_MECH_MIN_ICON=/home/evergarden/.icons/gladient/mech-min.png
++ NOTIF_EYC_ICON=/home/evergarden/.icons/gladient/eyc.png
++ NOTIF_EYC_MIN_ICON=/home/evergarden/.icons/gladient/eyc-min.png
++ NOTIF_WALLY_ICON=/home/evergarden/.icons/gladient/wally.png
++ NOTIF_MUSIC_ICON=/home/evergarden/.icons/gladient/music.png
++ NOTIF_SS_ICON=/home/evergarden/.icons/gladient/shot.png
++ TERM_ICON=/home/evergarden/.icons/gladient/term.png
++ DEFAPPS_EXEC=/home/evergarden/.scripts/default-apps/launch
++ EXNOTIFY_SEND=/home/evergarden/.scripts/notify/notify-send.sh
++ BRIGHTNESS_HANDLER=/home/evergarden/.scripts/notify/change-brightness
++ AVOLUME_CHANGER=/home/evergarden/.scripts/notify/change-volume
++ MUSIC_CONTROLLER=/home/evergarden/.scripts/music-controller
++ SS_NOW=/home/evergarden/.scripts/shot-now
++ SS_DRAW=/home/evergarden/.scripts/shot-seldraw
++ SS_TIMER=/home/evergarden/.scripts/shot-timer
++ MPD_TCD=/home/evergarden/.ncmpcpp/scripts/track-change-detector
++ user_pref
++ COL_WHTE='#f9f9f9'
++ COL_RETA='#f48ee8'
++ COL_REDZ='#fa74b2'
++ COL_RELE='#e88ef4'
++ COL_BLUE='#63c5ea'
++ COL_BLLE='#ac8ef4'
++ COL_GREE='#44eb9f'
++ MECH_START_BTN=
++ EYEC_START_BTN=
++ MECH_TINT2_GRAD1='#f48ee8'
++ MECH_TINT2_GRAD2='#fa74b2'
++ MECH_ROFI_ACCENT='#f48ee8'
++ MECH_ROFI_FRGRND='#f9f9f9'
++ MECH_DUNST_SMMRY='#f9f9f9'
++ MECH_DUNST_PRGBR='#f48ee8'
++ MECH_OB_MENU_TTL='#fa74b2'
++ MECH_OB_MENU_ITM='#f48ee8'
++ MECH_MIN_ROFI_ACCENT='#f9f9f9'
++ MECH_MIN_ROFI_FRGRND='#f9f9f9'
++ MECH_MIN_DUNST_SMMRY='#f9f9f9'
++ MECH_MIN_DUNST_PRGBR='#f9f9f9'
++ MECH_MIN_OB_MENU_TTL='#f9f9f9'
++ MECH_MIN_OB_MENU_ITM='#63c5ea'
++ EYEC_TINT2_GRAD1='#fa74b2'
++ EYEC_TINT2_GRAD2='#e88ef4'
++ EYEC_ROFI_ACCENT='#e88ef4'
++ EYEC_ROFI_FRGRND='#fa74b2'
++ EYEC_DUNST_SMMRY='#63c5ea'
++ EYEC_DUNST_PRGBR='#fa74b2'
++ EYEC_OB_MENU_TTL='#63c5ea'
++ EYEC_OB_MENU_ITM='#fa74b2'
++ EYEC_MIN_ROFI_ACCENT='#e88ef4'
++ EYEC_MIN_ROFI_FRGRND='#fa74b2'
++ EYEC_MIN_DUNST_SMMRY='#e88ef4'
++ EYEC_MIN_DUNST_PRGBR='#44eb9f'
++ EYEC_MIN_OB_MENU_TTL='#e88ef4'
++ EYEC_MIN_OB_MENU_ITM='#fa74b2'
++ DUNST=95
++ URXVT=95
++ WEB_BROWSER='brave-bin --use-gl=desktop --enable-features=VaapiVideoDecoder'
++ INT_ETH=enp4s0
++ INT_WIFI=wlan0
++ TEMP_DEV=cooling_device0
++ SAVE_SS=yes
++ SAVE_DIR=/home/evergarden/Pictures
++ COPY2CLIP=yes
++ ENABLE_FRAME=yes
++ FRAME_COLOR='#434c5e'
++ FRAME_PADDING=15
++ OPEN_FRAMED=no
++ FRAMED_SHADOW_OPACITY=25
++ TIMER_SEC=5
++ QUALITY=100
++ AUTOLOCK_MINUTE=5
++ AUDIO_STEPS=5
++ BRIGHTNESS_STEPS=5
++ NCMPCPP_ALBUMART_BACKEND=w3m
+ R='\e[1;31m'
+ M='\e[1;35m'
+ W='\e[1;37m'
+ NC='\e[0m'
+ r='\e[0;31m'
+ case ${1} in
+ grep -Fqo filemanager= /home/evergarden/.scripts/default-apps/list.joy
++ grep -oP 'filemanager="\K[^"]+' /home/evergarden/.scripts/default-apps/list.joy
+ EXEC=thunar
+ '[' -n '' ']'
+ '[' -n filemanager ']'
++ thunar
+ exec
+ exit 0
 

**Comment by owl4ce** [comment]
Sorry for the issue, but I don't know what's going on since everything is normal.
No other users also commented for experiencing this.
