### ISSUE TITLE
Icons gets messed up after installing some fonts [Bug]

### ISSUE THREAD

**Issue by YasirRWebDesigner** [owl4ce/dotfiles#169]
**Bug Description**
I install the following fonts and it causes the icons to be replaced with Urdu/Arabic script letters. I am referring to icons being used in scripts like `.config/rofi/scripts` I can't say if it is they same for tint2 as well, As I have already changed those icons, I did fix it by going to Nerd Font's website and copy pasting/replacing the icons being used in the script files.
- [ttf-x2](https://aur.archlinux.org/packages/ttf-x2)
- [ttf-urdufonts](https://aur.archlinux.org/packages/ttf-urdufonts)

**Expected behavior**
It shouldn't replace the icons with letters in the script files.

**Screenshots**
I forgot to take any.

**Desktop**
- **OS** Arch Linux
- **DE** Openbox
- **Shell** zsh

**Work Around/Fix**
For Now I replaced as many icons I could in the tint2 and the scripts as I could. I haven't seen any other icons other than `./config/rofi/scripts/` being replaced with Urdu/Arabic script/letters but I will add if I did.

**Recreate the issue**
Just install the following fonts from the aur and you will see the issue, in powermenu, mdp/spotify scripts.
- [ttf-x2](https://aur.archlinux.org/packages/ttf-x2)
- [ttf-urdufonts](https://aur.archlinux.org/packages/ttf-urdufonts)

**Comment by owl4ce** [comment]
In which branch did you install the dotfiles? I've unmaintained from the `main` branch for now, I'm working on the `ng` branch. Yes a lot of misconfiguration for the latest dependencies, especially the rofi fonts.
