### ISSUE TITLE
Invalid output from pipe-menu "/usr/bin/obmenu-generator -i"

### ISSUE THREAD

**Issue by maccree** [owl4ce/dotfiles#17]
![Pictures](https://user-images.githubusercontent.com/36086205/97788518-914cb800-1bca-11eb-9487-b384de25839d.jpeg)

ArchLinux 2020

**Comment by owl4ce** [comment]
install gtk2-perl

**Comment by maccree** [comment]
nothing

**Comment by maccree** [comment]
I installed gtk2-perl but nothing changed

**Comment by linuxmobile** [comment]
> I installed gtk2-perl but nothing changed

**yay -S obmenu-generator**

**Comment by maccree** [comment]
> > I installed gtk2-perl but nothing changed
> 
> **yay -S obmenu-generator**

I tried it but it didn't help
