### ISSUE TITLE
Missing emoji font (cherry blossom emoji) [Bug]

### ISSUE THREAD

**Issue by Maximumtix** [owl4ce/dotfiles#176]
**Describe the bug**
noto-fonts-emoji font is missing from the README thus commit https://github.com/owl4ce/dotfiles/commit/b626eba609d6f7ddb26d9010df92bd0bef762bac doesn't work

I fixed the bug by installing noto-fonts-emoji from the Artix Linux repos but you should add the font file to [Installation Prerequisites](https://github.com/owl4ce/dotfiles#hibiscus--installation-prerequisites), if that's not possible add the package to [Installation (Dependencies)](https://github.com/owl4ce/dotfiles#blossom--installation-dependencies)

**Comment by owl4ce** [comment]
**Thanks!**

However, I refer to it as not mandatory, but precedence.
