### ISSUE TITLE
PulseAudio not working 

### ISSUE THREAD

**Issue by exceedc** [owl4ce/dotfiles#179]
PulseAudio stuck on "_Establishing connection to PulseAudio. Please wait..._ " after entering openbox session
![2022-04-19-235125_1366x768_scrot](https://user-images.githubusercontent.com/81560572/164056436-4faced79-c1ab-4b1a-a573-a0a5f563a169.png)

But when i go back to xfce-session it works again
![Screenshot_2022-04-19_23-53-12](https://user-images.githubusercontent.com/81560572/164056534-597a469a-89a8-4154-88ee-1283d6b35bb3.png)

**Comment by owl4ce** [comment]
Hmm, Manjaro. Probably [this commmit](https://github.com/owl4ce/dotfiles/commit/8e39a089248bd907176773c23a06b90bea8d2f5d). Can you comment out that line and login to openbox-session again? @exceedc

**Comment by owl4ce** [comment]
Still wondering if it's caused by the same issue, even though conditional with the `pidof` and pulseaudio's built-in arguments.

**Comment by exceedc** [comment]
Commented line 21 on /.config/openbox/autostart.sh, it's working again now
Thanks @owl4ce
