### ISSUE TITLE
Issue with implementing theme

### ISSUE THREAD

**Issue by Partha2003** [owl4ce/dotfiles#181]
Hi, i am new to linux. I did everything as your instructions said(which is quite well put together honestly) but i can't get the rsync command working as this is error i get. Also after i moved to a new openbox session but the theme didn't took place. 
![Screenshot_2](https://user-images.githubusercontent.com/96782754/169570885-1dafa755-5c7b-4de4-9092-5869316bf16d.png)

**Comment by owl4ce** [comment]
Hi @Partha2003 

Sorry to hear that, I forgot to mention at the first regarding the heredocs, but it was mentioned at [SYNC FOR UPDATES](https://github.com/owl4ce/dotfiles#sunflower--sync-for-updates). It only works in POSIX-compliant shells, whereas **fish** is a [modern shell](https://fishshell.com/docs/current/design.html).

Instead, use your distro's default shell such as **bash**, **zsh**, or **dash** only for commands that use `<<` (heredocs).

**Comment by owl4ce** [comment]
**P.S.**

This is not just theme, but a whole set of interrelated configurations based on the Openbox Window Manager.

_So it's not as easy as installing and uninstalling like themes or packages._
