### ISSUE TITLE
Network and wallpaper issue

### ISSUE THREAD

**Issue by Partha2003** [owl4ce/dotfiles#182]
Hi i managed to finish applying the theme but wierdly enough i cannot apply wallpapers even though they are kept in the proper directory and for some reason I am being disconnected from the network whenever I choose to open a openbox session. I still am a linux begginer so i don't really know what's the exact issue.

**Comment by owl4ce** [comment]
**Please include your details, OS, etc.** I'm not a psychic who can know what I don't.

**Comment by owl4ce** [comment]
Also check your NetworkManager(?) journal/syslog, or kernel ring buffer `dmesg` to see what actually happens.

**Comment by owl4ce** [comment]
I'm not sure about your wallpaper issue, but it should work normally with `nitrogen` and its shell-scripts.

## Can you show a demonstration as a video or a gif?

**Comment by Partha2003** [comment]
My apologies, i should have posted it beforehand.

OS: Garuda Linux
Host: HP 87B2
Kernel: 5.17.9-zen1-1-zen
Packages: 1283 (pacman)
Shell: bash
WM: Openbox
WM Theme: Fleon
CPU: AMD Ryzen 5 4600H with Radeon Graphics (12)
GPU: AMD ATI Renoir
GPU: NVIDIA GeForce GTX 1650 Ti Mobile
Memory: 2.35GiB / 15.06GiB
Kernel: 5.17.9-zen1-1-zen arch: x86_64 bits: 64 compiler: gcc v: 12.1.0
Desktop: Openbox v: 3.6.1 
info: tint2 
vt: 1 
dm: SDDM 
base: Arch Linux

The network issue is solved as i read that you used networkmanager so i used it to connect to wifi and it worked. But the wallpaper issue still persists.

**Comment by owl4ce** [comment]
Does the wallpaper not change after selecting it from the selector interface (**rofi**) opened from the button in the panel (**tint2**)?

**Comment by Partha2003** [comment]
> Does the wallpaper not change after selecting it from the selector interface (**rofi**) opened from the button in the panel (**tint2**)?

No it does not unfortunately

**Comment by owl4ce** [comment]
> No it does not unfortunately

But the selector interface appears right?

**Comment by Partha2003** [comment]
> I'm not sure about your wallpaper issue, but it should work normally with `nitrogen` and its shell-scripts.
> ## Can you show a demonstration as a video or a gif?

Thanks for the comment managed to solve it, turns out nitrogen was not installed, furthermore if i were to just drop wallpapers on the folder i can switch it using rofi right? Hoping that no further configuration is needed?

Also to actually use the Windows key to launch the app launcher, where should i configure it exactly? along with adding other apps directly on the tint2 panel.

Lastly i can not find any network options to see speed or configure to change connections.

My apologies, my problems were too basic as it seems and also thank you for creating this truly incredible theming!

**Comment by owl4ce** [comment]
> .., turns out nitrogen was not installed, furthermore if i were to just drop wallpapers on the folder i can switch it using rofi right? Hoping that no further configuration is needed?

Yes, it should have paid attention to everything as per [README.md](https://github.com/owl4ce/dotfiles#blossom--installation-dependencies).

> Also to actually use the Windows key to launch the app launcher, where should i configure it exactly? ..

Sorry, but Openbox Window Manager can't do that. OpenboxWM requires at least two keys to be chained together.

> .. along with adding other apps directly on the tint2 panel.

Install and configure it with `tint2conf` program.

> Lastly i can not find any network options to see speed or configure to change connections.

Mostly, I use `nm-applet` to configure the network.
## Where I have included everything in the README.md.
