### ISSUE TITLE
Need to restart UI on login [Bug]

### ISSUE THREAD

**Issue by Partha2003** [owl4ce/dotfiles#184]
**The bug**
I was having a issue with making a item autostart so i used the option of the openbox autostart but unfortunately after just adding a few lines gives me blackscreen on boot everytime and i have to right click and restart UI. I tried undoing changes made to it but it still remains the same. 

**Expected behavior**
After undoing changes it should go back to showing the desktop normally as usual but it does not.

**Screenshots**

![0b189d44-48c0-402c-8685-ccba8ae23db6](https://user-images.githubusercontent.com/96782754/170811753-f5af24b0-31fe-4218-a39b-3daafeec1fae.jpg)

My apologies but i can only seem to use a camera here.

**Desktop (please complete the following information):**
 - **OS**: [Arch Linux]

**Additional context**

I tried restarting both tint2 and Openbox but i have to restart UI or else it doesn't seem to show the normal desktop.

**Comment by owl4ce** [comment]
Does resyncing the dotfiles fix the issue?

**Comment by owl4ce** [comment]
*Even I synced this to ([these](https://github.com/owl4ce/dotfiles/tree/ng/EXTRA_JOYFUL/.config/neofetch/images)) various Linux distributions, got no problem at all.*

**Comment by owl4ce** [comment]
Ensure not to change these lines, but addition should be OK.

https://github.com/owl4ce/dotfiles/blob/bc5f43a44dea5b94bf56c0f20506db034509634e/.config/openbox/autostart.sh#L1-L41

<a href="https://github.com/owl4ce/dotfiles#herb--guides"><p align="center"><img alt="" src="https://user-images.githubusercontent.com/53987136/170812565-e0002838-c3e9-427b-afd0-5880b82bb550.png"/></p></a>

**Comment by Partha2003** [comment]
> Does resyncing the dotfiles fix the issue?

Resync restores the desktop but on restart it still goes black screen again.

**Comment by Partha2003** [comment]
> Ensure not to change these lines, but addition should be OK.
> 
> https://github.com/owl4ce/dotfiles/blob/bc5f43a44dea5b94bf56c0f20506db034509634e/.config/openbox/autostart.sh#L1-L41
> 
> [![](https://user-images.githubusercontent.com/53987136/170812565-e0002838-c3e9-427b-afd0-5880b82bb550.png)](https://github.com/owl4ce/dotfiles#herb--guides)

I think this might fix it.

**Comment by Partha2003** [comment]
> Ensure not to change these lines, but addition should be OK.
> 
> https://github.com/owl4ce/dotfiles/blob/bc5f43a44dea5b94bf56c0f20506db034509634e/.config/openbox/autostart.sh#L1-L41
> 
> [![](https://user-images.githubusercontent.com/53987136/170812565-e0002838-c3e9-427b-afd0-5880b82bb550.png)](https://github.com/owl4ce/dotfiles#herb--guides)

I had to copy the lines and paste it again for it work, thanks!

I am using openbox community edition as of now, and it seems like the autostart file was a bit different.

**Comment by owl4ce** [comment]
> I had to copy the lines and paste it again for it work, thanks!

Did you exclude `autostart.sh` based on the `*.sh` glob earlier?
I thought that resync should have been fixed because it synced everything.

> I am using openbox community edition as of now, and it seems like the autostart file was a bit different.

Hmm, any version of openbox should be normal.

**Comment by owl4ce** [comment]
_I think there's a misunderstanding here._

**Comment by Partha2003** [comment]
> _I think there's a misunderstanding here._

**It maybe due to my inexperience with linux, to clarify what i did :**

I did a fresh install of Endeavour Os openbox community edition and performed steps accordingly to your guide, for some reason the autostart configuration still remained to the old one which openbox came with when i installed the Os. I rsynced and checked but nothing really happened. Afterwards i removed whatever was in the openbox autostart and pasted yours and welp it worked!

**On a sidenote a random question, before you close this thread so there is not another random thread:**

I am creating buttons in pannel without any problems it's just that i wanted to know how exactly you pasted the PUA Emoticon.

**Comment by owl4ce** [comment]
> how exactly you pasted the PUA Emoticon.
Or is there anyway to make a PNG be a button icon?

Install `gucharmap` and use.

**Comment by owl4ce** [comment]
> for some reason the autostart configuration still remained to the old one which openbox came with when i installed the Os.

Oh, it's probably because the Openbox configuration on your system is newer (or somehow).
So `rsync` flags it doesn't need to be replaced with the one in dotfiles.

**Comment by owl4ce** [comment]
Well, actually I'm recommending a clean base-distro instead of being provided by the community. 
So from the beginning install the new packages.

**Comment by owl4ce** [comment]
Actually I've also given some hints in [this discussion](https://github.com/owl4ce/dotfiles/discussions/64#discussion-3251765), but maybe I misplaced the information.

I'm apologize if I'm a bit stiff in answering your question (recently), as I've been a bit busy.
