### ISSUE TITLE
Spotify theming doesn't work.

### ISSUE THREAD

**Issue by Partha2003** [owl4ce/dotfiles#186]
As you mentioned in your readme Spotify is integrated by default but it's not working for me for some reason. I followed your readme exactly and did install everything you mentioned. I got Spotify from AUR repo before synchronising files again but nothing really happened, it stayed the same.

I reinstalled Spotify, and re synced again but issue still persists.

In your YouTube demonstration audio controls work and tittle track information is shown, but it does not unfortunately work for me. Track controls don't work too.

Hopefully it's just some silly integration issue on my end, if you could advise on this i would be very grateful.

![IMG_20220603_130120_542](https://user-images.githubusercontent.com/96782754/171808693-943af731-82c2-4d83-b644-b600e3a7ef55.png)

**Comment by owl4ce** [comment]
# `Integrated` != `Theming`

As the pre-release of **Joyful Desktop 4**, I don't provide **spotify** (spicetify) themes anymore. Just controllable.

> In your YouTube demonstration audio controls work and tittle track information is shown, but it does not unfortunately work for me. Track controls don't work too.

My YouTube videos are outdated. However for init-freedom distros, ensure `dbus` and `elogind` is started.

**Right now, I don't know what's really going on your machine. My machine works well.**
