### ISSUE TITLE
.zshrc file is unedited

### ISSUE THREAD

**Issue by 401-No-Username** [owl4ce/dotfiles#189]
I did a fresh install of v.4 and am fairly certain I followed every step correctly however I noticed oh-my-zsh wasn't running plugins (fast-syntax-highlighting, zsh-autosuggestions, zsh-completions). I was unable to find the .zshrc file in the dotfiles or installation process and manually added the plugins to the file myself. 
Opening a issue request as 1) I imagine this isn't the intent as zsh won't load the downloaded plugins 2) when I viewed the .zshrc that was previously listed in v.3 it had other tweaks (mainly a lot of allias's) that I am missing and am unsure if I should copy and paste it into v.4's environment.

**Comment by owl4ce** [comment]
# Why don't you check `EXTRA_JOYFUL` directory?

**Comment by 401-No-Username** [comment]
ah as I feared, I just missed it
