### ISSUE TITLE
Chrome theme issues

### ISSUE THREAD

**Issue by aravind987** [owl4ce/dotfiles#19]
The background of a few things in Chrome is messed up. The popup that shows up when you hover over a tab is not opaque and hard to see. The backgrounds of the Extensions menu is also messed up like shown in the pictures. 
![2020-11-12-102040_1366x768_scrot](https://user-images.githubusercontent.com/50051060/98959921-c9f56700-24d1-11eb-8fec-acc6d5c5f2a3.png)
![2020-11-12-102611_1366x768_scrot](https://user-images.githubusercontent.com/50051060/98959926-ca8dfd80-24d1-11eb-8551-f9a3ed84c3e3.png)
I went on incognito to take the screenshots but this also occurs outside of incognito. Is this a problem with the GTK theme or my compositor?

**Comment by owl4ce** [comment]
Sorry, customize chrome/ium light theme very tricky. This is permanent problem.

**Comment by owl4ce** [comment]
**Hi @aravind987**
Now, I have fixed this issue. https://github.com/owl4ce/dotfiles/commit/70a6d379aa52d2e0bbe98810532256dc4082aae7
https://github.com/owl4ce/dotfiles/blob/87a1a01b6044531c2b7430d43e2dcabde98e24e7/.themes/Sweetly/gtk-3.22/gtk.css#L4766-L4771

<p align="center"><img src="https://i.ibb.co/55fvV30/2021-02-02-153019-1366x768-scrot.png"/></p>
