### ISSUE TITLE
Cant open shortcuts [Bug]

### ISSUE THREAD

**Issue by Asterdux1** [owl4ce/dotfiles#190]
For some reason when I press shortcuts for example the super / windows key a dialog comes up saying:
Failed to launch shortcut "<Alt>F1"
Failed to execute child process "xfce4-popup-whiskermenu" (No such file or directory)

OS is arch linux

Im not that good with linux for now, so i dont know if I did something wrong or if its a bug, please help me

**Comment by owl4ce** [comment]
I don't know. This is not my dotfiles-specific. Probably your DE, because my Openbox configuration doesn't use any function keybindings (F1-F12).
