### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by TechWiz-3** [owl4ce/dotfiles#191]
https://owl4ce.github.io/iolr is broken, I'm assuming you know because it's striked through?

The Indonesian version is fine, is there one in English?

**Comment by owl4ce** [comment]
**Hi @TechWiz-3**

Yeah, sorry about that. Currently only provides the Indonesian version, I haven't had time to write the English version.

**Comment by TechWiz-3** [comment]
All g, thanks for the response 👍
