### ISSUE TITLE
Thunar side pane picture

### ISSUE THREAD

**Issue by mrlinuxdude** [owl4ce/dotfiles#192]
How can i get picture in Side pane in thunar? Do i need anything installed, or have to do anything. Thanks

**Comment by owl4ce** [comment]
**Template:** https://github.com/owl4ce/dotfiles/discussions/64#discussion-3251765
**Raw:** [[Fleon](https://github.com/owl4ce/dotfiles/blob/ng/.themes/Fleon/gtk-assets/thunar-sidebar.png)] [[Sweetly](https://github.com/owl4ce/dotfiles/blob/ng/.themes/Sweetly/gtk-assets/thunar-sidebar.png)]

**CSS:**
https://github.com/owl4ce/dotfiles/blob/6603b0d21cfe49174aff041495a8be45f45209f3/.themes/Fleon/gtk-3.0/custom.css#L63-L65
