### ISSUE TITLE
Missing dim brightness option and storage info in Rofi

### ISSUE THREAD

**Issue by ferroson** [owl4ce/dotfiles#196]
**Describe the bug**
I saw the df command in the config, I think it's used to display storage info. As seen in the screenshot, the storage info is gone (showing only @ instead). The dim brightness option is also missing

**Expected behavior**
Storage info and dim brightness options should appear

**Screenshots**
![2022-09-08-112003_1366x768_scrot](https://user-images.githubusercontent.com/108534456/189035606-078d618c-00b8-4efa-803b-1d1369db2d6e.png)
![2022-09-08-112012_1366x768_scrot](https://user-images.githubusercontent.com/108534456/189035645-55dd7b82-2e8c-4d60-8dca-3e95504c0908.png)
![2022-09-08-113743_581x349_scrot](https://user-images.githubusercontent.com/108534456/189035695-ea7397e7-fadb-468c-a6da-0a68bb6df169.png)

**Desktop (please complete the following information):**
Archcraft (I changed os-release as Garuda Linux because it uses chaotic-aur by default and I removed the Archcraft repo)

**Additional context**
(none)

**Comment by owl4ce** [comment]
> Dim brightness doesn't go away, just need to scroll to see the options, ...

Yeah, probably because of the screen resolution and DPI, but it's definitely pixel-perfect on my device. **1366x768 96 DPI**. The rofi menu options are not cropped.

The only solution, you could adjust this to higher value:
https://github.com/owl4ce/dotfiles/blob/8432870912620d45120effa97aa378cf9a9694e7/.config/rofi/themes/shared.rasi#L23

---

> ... but I don't know what the df command is for in rofi, am I really missing something?

Can you tell the output of the full `df` command as per the shell-script on your system?

```sh
$ df -l -h --output='source,pcent,fstype'
```

I suspect something doesn't match the preferences there with the preferences on my system ... :thinking:

**Comment by owl4ce** [comment]
> I suspect something doesn't match the preferences there with the preferences on my system ... :thinking:

Maybe it's because of Gentoo's preference to use `/dev/root` which is symlinked to the filesystem block-device (root), but on your system it directly uses the filesystem block-device (root), in this case `/dev/sda2`. If true then it needs some changes in the shell-script.

**Comment by owl4ce** [comment]
Just got the solution for `df`. Thank you for reporting the issue.

**Comment by ferroson** [comment]
> > Dim brightness doesn't go away, just need to scroll to see the options, ...
> 
> Yeah, probably because of the screen resolution and DPI, but it's definitely pixel-perfect on my device. **1366x768 96 DPI**. The rofi menu options are not cropped.
> 
> The only solution, you could adjust this to higher value:
> 
> https://github.com/owl4ce/dotfiles/blob/8432870912620d45120effa97aa378cf9a9694e7/.config/rofi/themes/shared.rasi#L24
> 
> > ... but I don't know what the df command is for in rofi, am I really missing something?
> 
> Can you tell the output of the full `df` command as per the shell-script on your system?
> 
> ```shell
> $ df -l -h --output='source,pcent,fstype'
> ```
> 
> I suspect something doesn't match the preferences there with the preferences on my system ... thinking

Thank you very much, adding 2-3% value in exts-window-height solved the dim option problem

The df command output on my computer looks like this:
  df -l -h --output='source,pcent,fstype'                            ~  
Filesystem     Use% Type
dev              0% devtmpfs
run              1% tmpfs
/dev/sda2       51% ext4
tmpfs            1% tmpfs
tmpfs           11% tmpfs
tmpfs            0% tmpfs
tmpfs            1% tmpfs
 
