### ISSUE TITLE
[ISSUE] Tint2 Network Disconnected

### ISSUE THREAD

**Issue by linuxmobile** [owl4ce/dotfiles#20]
**Tint2 show my wifi Disconnected**. i know this need to be changed in ~/.config/tint2/executor/network. **And i do this, change the value to my WIFI adapter name**... but not working.

![2020-11-16-161540_1366x768_scrot](https://user-images.githubusercontent.com/10554636/99278705-5207a380-2827-11eb-83af-00c754dabec4.png)
![2020-11-16-161604_1366x768_scrot](https://user-images.githubusercontent.com/10554636/99278723-5633c100-2827-11eb-8a39-1f5f461d9ae1.png)

**Comment by owl4ce** [comment]
Sorry for missing dependencies, try install wireless_tools :)
