### ISSUE TITLE
Ncmpcpp Album Art

### ISSUE THREAD

**Issue by Maximumtix** [owl4ce/dotfiles#21]
I have tried to name the album art in my folder many different things but not being able to understand shell script I failed to get it working at the end. Could you make a more detailed explanation about how to do it?

**Comment by owl4ce** [comment]
What's linux distro?

**Comment by owl4ce** [comment]
@Maximumtix 
I fixed it.
https://github.com/owl4ce/dotfiles/commit/15b2efa335adbb554a71cd49d3b89c7114087d2c
