### ISSUE TITLE
[ISSUE] ncmpcpp file not found but it reproduce

### ISSUE THREAD

**Issue by linuxmobile** [owl4ce/dotfiles#22]
This happen... Not such file or directory but music work...

![2020-11-23-125229_581x270_scrot](https://user-images.githubusercontent.com/10554636/99983569-c774f600-2d8a-11eb-9a89-269b880c4489.png)

**Comment by owl4ce** [comment]
There are two slashes lined up, try to check or delete the last slash in the mpd and ncmpcpp directory configuration.

**Comment by linuxmobile** [comment]
> slashes lined up

**I do, but nothing happen...** 
### Two slash dissapear but now show find:` '~/Music/NAME OF SONG.mp3': No such file or directory`
![2020-11-24-214448_531x701_scrot](https://user-images.githubusercontent.com/10554636/100167686-5aeb1b80-2e9e-11eb-8a38-6e01292c256f.png)

**Comment by linuxmobile** [comment]
### Hi, i can detect the problems is the scripts in: album, album and visualizer and album only... Check pls the scripts.--

**Comment by owl4ce** [comment]
I don't know why, but I switched linux distributions recently and it's working normally.

**Comment by owl4ce** [comment]
I fixed it
