### ISSUE TITLE
Terminal icons weird

### ISSUE THREAD

**Issue by kadenscott** [owl4ce/dotfiles#23]
Hi! First off, I want to say really nice job with this theme. Really makes the introduction to Arch an awesome experience :smile:

Anyways, onto the issue. Icons in the terminal seem to have a weird effect, as if they were being squished and not all pixels could be rendered.

Here is an image: https://imgur.com/a/RMI7w6e
Another image: https://imgur.com/a/2kymxVC

I'm not sure if this is related, but using the keybinds to change font size results in the font size _not_ changing, but with all text being offset and it all acts pretty buggy.

This is running the latest v3 of your dotfiles.

I wanted to make sure this wasn't related to #3, but as this is to do with urxvt and not rofi, I thought it would be more appropriate to make a new issue.

Let me know if you need any more information. Thanks!

EDIT: Just wanted to note that I am using a 1080x1920 resolution display.
EDIT2: Also wanted to note that this bug also appears within IntelliJ's console. https://imgur.com/a/eAaZMYN

**Comment by owl4ce** [comment]
Thanks for telling. I forgot to turn this off, because I'm on Gentoo Linux the fonts are wide and I press with this. Debian & Arch should have an exclamation mark.
![2020-11-29-221935_373x36_scrot-wFRAME](https://user-images.githubusercontent.com/53987136/100545924-075b4200-3291-11eb-96be-48d0ed0e0152.png)

**Comment by kadenscott** [comment]
Thanks for the quick response!
I have changed line 19 of my Xresources to `!URxvt.letterSpace: -1` yet the bug still appears. I'll play around with different letterspacing options to see if that changes anything.
