### ISSUE TITLE
[ISSUE] nvim error in V3

### ISSUE THREAD

**Issue by linuxmobile** [owl4ce/dotfiles#24]
I update all things in V3 build.

![2020-11-29-132047_498x334_scrot](https://user-images.githubusercontent.com/10554636/100548811-ac542b80-324d-11eb-9734-4c817e3829ba.png)

**Comment by owl4ce** [comment]
Sorry I forgot to comment, it should be disabled for initial setup all plugins.

![2020-11-30-010603_394x273_scrot-wFRAME](https://user-images.githubusercontent.com/53987136/100549866-45179500-32a8-11eb-9df9-412180cd7cf7.png)

Then continue with https://github.com/junegunn/vim-plug.

**Comment by linuxmobile** [comment]
Yes, know works but i've got this!

![2020-11-29-171423_581x334_scrot](https://user-images.githubusercontent.com/10554636/100552516-6d7e9f80-3266-11eb-9d65-ed0315ff878f.png)

**Comment by owl4ce** [comment]
Try deleting or commenting this
![2020-11-30-033406_566x252_scrot-wFRAME](https://user-images.githubusercontent.com/53987136/100552917-f3c5d080-32bc-11eb-8111-3ccbcdf6c3f7.png)
