### ISSUE TITLE
V3 Background and sidebar doesn't work

### ISSUE THREAD

**Issue by aravind987** [owl4ce/dotfiles#25]
Updating to V3 and then restarting Openbox works fine but as soon as I reboot, the background turns grey and the sidebar does not show up. I am still able to start apps and everything with shortcuts though

**Comment by owl4ce** [comment]
Sorry, the problem will be hard to find in that case. Hmm, how should I ...

**Comment by aravind987** [comment]
![2020-11-29-200627_1366x768_scrot](https://user-images.githubusercontent.com/50051060/100559060-10431800-327f-11eb-85ed-84cae5b3bf5e.png)
This is just what it looks like. Also your V2 worked fine for me with no problems so its gotta be something that changed from V2 to V3 if that helps

**Comment by aravind987** [comment]
One more thing urxvt is completely pink for some reason. Probably not related but just in case, it looks like this: 
![2020-11-29-201910_1366x768_scrot](https://user-images.githubusercontent.com/50051060/100559338-4208ae80-3280-11eb-9ae5-f047564fd792.png)

**Comment by aravind987** [comment]
Okay so I managed to fix this. I just looked at the differences between your V2 openbox autostart and your V3 autostart.
Adding the following lines from your V2 fixes the issue:

# UI Appearance - Open Last Theme
bash -c '~/.config/openbox/visual-mode/startup'

# Start Tray
bash -c '~/.config/openbox/tray' &> /dev/null
