### ISSUE TITLE
Icons fonts looks like weird 

### ISSUE THREAD

**Issue by linuxmobile** [owl4ce/dotfiles#3]
![2020-08-18-210433_2806x900_scrot](https://user-images.githubusercontent.com/10554636/90577292-e023ad80-e196-11ea-89d5-93914c56b1a2.png)
![2020-08-18-210516_2806x900_scrot](https://user-images.githubusercontent.com/10554636/90577296-e44fcb00-e196-11ea-9749-b57dea31fd71.png)

**Comment by owl4ce** [comment]
What screen resolution are you using? Mine is **1366x768**, I don't know of any problems with higher resolutions.

**Comment by linuxmobile** [comment]
> What screen resolution are you using? Mine is **1366x768**, I don't know of any problems with higher resolutions.

Me too. I'm using 1366x768.

**Comment by owl4ce** [comment]
![2020-09-07-170436_1366x768_scrot](https://user-images.githubusercontent.com/53987136/92376080-3e0b3b80-f12c-11ea-9371-35ec07cd2a2d.png)

oh no, today I upgraded arch linux and something similar happened.

**Comment by owl4ce** [comment]
![2020-09-07-201759_532x520_scrot](https://user-images.githubusercontent.com/53987136/92392128-fe524d00-f147-11ea-8638-b591ebe51d61.png)

*solved: downgrade rofi to version 1.5.4*

**Comment by opxop** [comment]
in debian the font icons still looks weird even though I have tried it in the stable (v1.5.1) and unstable (v1.5.4) versions.

**solution**
just decrease `icon-font` size in `~/.config/rofi/themes/sidebar`; _default 18px_
![2020-09-28_09-37](https://user-images.githubusercontent.com/49778014/94385224-c9e21780-016e-11eb-9ea3-dddd12803861.png)

Idk if the problem is only my machine or not, but hopefully it can help other debian users :grimacing:

thanks for this cute theme @owl4ce

**Comment by trinadhthatakula** [comment]
![2020-10-20-121943_1920x1080_scrot](https://user-images.githubusercontent.com/33689525/96550535-a114f400-12ce-11eb-8e0a-c0733da02547.png)

I am still facing this issue even after downgrading rofi to 1.5.4.2 
My screen size is 1920x1080 is that the reson for this

**Comment by maccree** [comment]
the same problem as here: https://github.com/owl4ce/dotfiles/issues/3#issuecomment-712634696
Manjaro x86_64

**Comment by EvoSteven** [comment]
The power menu is related to the resolution I think.

Open ~/.config/rofi/themes/sidebar/five.rasi with a text editor and go to line 13

`#window {
  width: 6%;
  height: 46%;
  anchor: east;
  location: east;
  x-offset: -1%;
  y-offset: 0%;
  border: 0px;
}`

To make it resolution independent, change width and height to something like:

`  width: 82px;
  height: 345px;`
