### ISSUE TITLE
run without python2

### ISSUE THREAD

**Issue by Yofo-me** [owl4ce/dotfiles#30]
could it run with python3?(Not depends on python2.)

**Comment by owl4ce** [comment]
python2 is actually only for the desktop menu (right click) that sets the resolution, etc. I haven't had the chance to port the script into python3. Maybe someone can, I accept contributions :)

**Comment by owl4ce** [comment]
**Hi @Yofo-me, I've removed the python2 dependency.**
Thanks to @mochidaz for porting [obrandr](https://github.com/owl4ce/dotfiles/blob/master/.config/openbox/pipe-menu/ob-randr.py) from python2 to python3.

[See PR](https://github.com/owl4ce/dotfiles/pull/31)
