### ISSUE TITLE
Rofi matched lines indicator

### ISSUE THREAD

**Issue by vredesbyyrd** [owl4ce/dotfiles#33]
Hi, I am loving your rofi themes. I am trying to add the matched-lines-indicator widget to the appsmenu theme, but struggling to get it to display correctly. 

[relevant rofi issue](https://github.com/davatorium/rofi/issues/1026)

Is this something you would be willing to add to your themes? I have no problems adding to my own rofi themes but have not had any luck with yours. Any pointers would be appreciated... apologies for the perhaps petty issue.

**Comment by owl4ce** [comment]
**Hi @vredesbyyrd** 
Do you mean like this?

![2020-12-29-115519_1366x768_scrot](https://user-images.githubusercontent.com/53987136/103259636-d1fb5e80-49cc-11eb-85a5-6978b20763ee.png)

**Comment by vredesbyyrd** [comment]
Sorry, in the doc its actually referenced as `num-filtered-rows`.  [theme markdown](https://github.com/davatorium/rofi/blob/next/doc/rofi-theme.5.markdown)

Notice the indicator @ topright.  My brain was refusing to work yesterday, i probably could figure it out with a closer look today.

![rofi-2020-12-29-1151-00000](https://user-images.githubusercontent.com/22080838/103304246-be042c80-49cd-11eb-8eb8-b052f08324b6.png)

**Comment by owl4ce** [comment]
**Hi @vredesbyyrd** 
I accept your recommendation. But I've been busy lately so I'm only accepting PR and will just merge it. Of course I will review it first.

**Thank you!**

**Comment by vredesbyyrd** [comment]
Right on. Not sure ill get to it today, but I will get it done and make a PR sooner than later.

**Comment by vredesbyyrd** [comment]
I'm working on a new laptop without git setup yet, but for now here is a patch for appsmenu that adds the "indicator" to the entry. Thanks again for the great theme. 

```diff
--- appsmenu.rasi.orig	2021-01-01 16:08:17.639890000 -0600
+++ appsmenu.rasi	2021-01-01 16:26:31.229863514 -0600
@@ -17,12 +17,17 @@
 inputbar,
 prompt,
 textbox-prompt-colon,
+indicator,
+num-filtered-rows,
+textbox-sep,
+num-rows,
 entry {
   background-color: @background-light;
 }
 
+
 #inputbar {
-  children: [ prompt, textbox-prompt-colon, entry ];
+  children: [  prompt, textbox-prompt-colon, entry, indicator ];
   margin: @inputbar-margin;
   border-radius: 8px;
 }
@@ -45,6 +50,24 @@
   padding: @entry-padding;
 }
 
+#indicator {
+  children: [ num-filtered-rows, textbox-sep, num-rows];
+  orientation: horizontal;
+  expand: false;
+  padding: 0 10px;
+}
+
+num-filtered-rows,
+textbox-sep,
+num-rows {
+  font: @prompt-menu-font;
+  text-color: @foreground;
+  expand: false;
+  str: "/";
+  vertical-align: 0.5;
+  padding: 0 2px;
+}
+
 #element {
   padding: @list-element-padding;
   margin: @list-element-margin;



```

General preview of what it looks like:

![rofi-2021-01-01-1628-00000](https://user-images.githubusercontent.com/22080838/103447348-b784e780-4c4f-11eb-90f4-35c2971b51d1.png)
