### ISSUE TITLE
something strange with fonts in zsh

### ISSUE THREAD

**Issue by maccree** [owl4ce/dotfiles#36]
![2021-01-08-154411_689x423_scrot](https://user-images.githubusercontent.com/36086205/104017138-9d578600-51c8-11eb-8f34-ca0898396aa2.png)
![2021-01-08-154354_674x489_scrot](https://user-images.githubusercontent.com/36086205/104017142-9f214980-51c8-11eb-9056-971f608804f3.png)

How do I fix this?

**Comment by owl4ce** [comment]
I'm not sure the problem is, have you set the [locale](https://wiki.archlinux.org/index.php/locale)?

**Comment by maccree** [comment]
> I'm not sure the problem is, have you set the [locale](https://wiki.archlinux.org/index.php/locale)?

Yes, of course
![2021-01-08-162041_787x490_scrot](https://user-images.githubusercontent.com/36086205/104019981-849d9f00-51cd-11eb-89c1-cb5be26f4791.png)

**Comment by maccree** [comment]
I reinstalled arch and everything returned to normal. Apparently somewhere I made a mistake when installing
