### ISSUE TITLE
Rofi icons in volume menu, screenshot menu, etc. not working [Bug]

### ISSUE THREAD

**Issue by ked1108** [owl4ce/dotfiles#37]
**Describe the bug**
Icons not showing in the screenshot, player control menu.

**Expected behavior**
Icons to work.

**Screenshots**
![image](https://user-images.githubusercontent.com/56258764/104282124-92586a80-54d4-11eb-8cb5-04bd44d66188.png)

**Desktop (please complete the following information):**
 - Ubuntu 20.10

**Comment by owl4ce** [comment]
What screen resolution are you using? Mine from 1366x768 to 1920x1080 is fine.
![2021-01-13-014429_1920x1080_scrot](https://user-images.githubusercontent.com/53987136/104358447-092b4d00-5541-11eb-979c-020ee7538e43.png)

**Comment by ked1108** [comment]
1920x1080

**Comment by owl4ce** [comment]
> 1920x1080

Rofi version?

![2021-01-13-015221_581x351_scrot](https://user-images.githubusercontent.com/53987136/104359304-11d05300-5542-11eb-86f6-49b30a87ff3b.png)

**Comment by ked1108** [comment]
Ooh, I am using rofi 1.5.4, I guess that's what's causing the issue.

**Comment by owl4ce** [comment]
Yes, you have to [compile it](https://github.com/davatorium/rofi/blob/next/INSTALL.md) yourself. Given that Debian & Ubuntu aren't [bleeding-edge](https://en.wikipedia.org/wiki/Bleeding_edge_technology) distros.
> Except debian sid, maybe

**Comment by ked1108** [comment]
so I managed to install rofi 1.6.1-10 and everything is working just fine :^) thanks for the support!

**Comment by owl4ce** [comment]
Guys, rofi v1.7.x seems buggy? isn't it?

**Comment by sakkamade** [comment]
The 1.7.0 release removed a whole lot of deprecated features (read  https://github.com/davatorium/rofi/releases/tag/1.7.0).
 You may search through the issues and discussions there, to fix them. 
Move `colums: 3` from `configuration {  }` into the `listview {  }`, for example.

And yet, I still didn't resolve all problems, such as strange space in formatting after `{w}` (workspace).

**Comment by sheeepdev** [comment]
> Guys, rofi v1.7.x seems buggy? isn't it?

Yeah

**Comment by owl4ce** [comment]
> Yeah

**So many changes :)**

I'll adapt if the rofi on my distro (Gentoo) updated to `1.7.x`.
