### ISSUE TITLE
More formal theme [Feature Req]

### ISSUE THREAD

**Issue by hamadmarri** [owl4ce/dotfiles#41]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I love your ricing. The theme of rofi and all tint2 customizations are nice. I wish if you could make a theme that is less girly where I don't hesitate using it when someone watching. I think the heart icon for close button will make my wife asks if she married the right person. I am asking you please to make a new theme where it is somehow neutral and formal for daily use but at the same time still beautiful and eye candy.

Thank you so much

**Comment by owl4ce** [comment]
> **Is your feature request related to a problem? Please describe.**
> No
> 
> **Describe the solution you'd like**
> I love your ricing. The theme of rofi and all tint2 customizations are nice. I wish if you could make a theme that is less girly where I don't hesitate using it when someone watching. I think the heart icon for close button will make my wife asks if she married the right person. I am asking you please to make a new theme where it is somehow neutral and formal for daily use but at the same time still beautiful and eye candy.
> 
> Thank you so much

**Hi @hamadmarri** 
Actually, buttons, etc. can be changed by clicking icon on the panel, hovering to see its function.
[Some demos](https://www.youtube.com/c/HarrysLabs-owl4ce)

**Comment by hamadmarri** [comment]
> > **Is your feature request related to a problem? Please describe.**
> > No
> > **Describe the solution you'd like**
> > I love your ricing. The theme of rofi and all tint2 customizations are nice. I wish if you could make a theme that is less girly where I don't hesitate using it when someone watching. I think the heart icon for close button will make my wife asks if she married the right person. I am asking you please to make a new theme where it is somehow neutral and formal for daily use but at the same time still beautiful and eye candy.
> > Thank you so much
> 
> **Hi @hamadmarri**
> Actually, buttons, etc. can be changed by clicking icon on the panel, hovering to see its function.
> [Some demos](https://www.youtube.com/c/HarrysLabs-owl4ce)

The right click works for me, it aligned them to the left, but left click doesn't work for me.

Thank you

**Comment by owl4ce** [comment]
> > > **Is your feature request related to a problem? Please describe.**
> > > No
> > > **Describe the solution you'd like**
> > > I love your ricing. The theme of rofi and all tint2 customizations are nice. I wish if you could make a theme that is less girly where I don't hesitate using it when someone watching. I think the heart icon for close button will make my wife asks if she married the right person. I am asking you please to make a new theme where it is somehow neutral and formal for daily use but at the same time still beautiful and eye candy.
> > > Thank you so much
> > 
> > 
> > **Hi @hamadmarri**
> > Actually, buttons, etc. can be changed by clicking icon on the panel, hovering to see its function.
> > [Some demos](https://www.youtube.com/c/HarrysLabs-owl4ce)
> 
> The right click works, it aligned them to the left, but left click doesn't work for me.
> 
> Thank you

Yeah, it requires terminal to open when clicked. Is there a urxvt/termite package in your Linux distribution repo? It really doesn't have to be that way, but because I only have 2 terminals configured a uniform theme.

![2021-01-14-183846_783x273_scrot](https://user-images.githubusercontent.com/53987136/104586268-d9428d80-5697-11eb-8840-982948d1e8ba.png)

**Comment by hamadmarri** [comment]
I will try install urxvt

**Comment by hamadmarri** [comment]
It worked with rxvt-unicode

Thank you
