### ISSUE TITLE
The Theme is broken/logs into black screen

### ISSUE THREAD

**Issue by WakanaYuki** [owl4ce/dotfiles#42]
**Describe the bug**
Everytime I log in, I only get a black screen and nothing continues to load.

**Expected behavior**
It should start displaying the background and other widgets and controls (I am not sure, if picom or tint2 is broken, I suspect tint2).

**Desktop (please complete the following information):**
 - **OS**: Pop-OS (derived Ubuntu distro)

**Additional context**
This all happened after I installed the newest version today, I have used the version 1.2 (I think it was 1.2), 2 and 2.1 without having any problem before and I really really love this theme, thank you so much for all the great work you put into this ^^

**Comment by owl4ce** [comment]
Indeed, from version 1 and 2 it is very much different from version 3. Especially have to load [`~/.owl4ce_var`](https://github.com/owl4ce/dotfiles/blob/main/.owl4ce_var) file, because I center all the variables there.

**Comment by WakanaYuki** [comment]
I have tried executing that file but that didnt work. I still not boot into the theme :/
Is there any way to fix that? it seems like the auto startup script does not work or doesnt get executed.
Also all files are in my homedir.

**Comment by maccree** [comment]
same problem on ubuntu

**Comment by owl4ce** [comment]
Hey, try deleting the `~/.config/openbox/*` directory then copy again from this repo. Also don't forget to copy `~/.owl4ce_var` too.

Somehow it happens, maybe this is due to a conflict from the previous file (not replaced by rsync) and I don't understand the specific problem. So far I have tried repeatedly on my device and I have not experienced any problems.

Alternatively, try using `cp -a` instead of `rsync` to re-copy all files from this repo. Except `.git`,`.github`,`README.md`,`LICENSE`.

**Comment by WakanaYuki** [comment]
I have already tried copying all the files without rsync. I could try downloading the repo again and then not using rsync but copying them directly.

I do still have to try deleting the openbox config, even though I very much suspect it being a broken script or something weird. I will still try this as soon as I get to my PC. But yeah running owl4ce_var manually also didn't do much for me :/

**Comment by maccree** [comment]
> I have already tried copying all the files without rsync. I could try downloading the repo again and then not using rsync but copying them directly.
> 
> I do still have to try deleting the openbox config, even though I very much suspect it being a broken script or something weird. I will still try this as soon as I get to my PC. But yeah running owl4ce_var manually also didn't do much for me :/

exactly the same

**Comment by owl4ce** [comment]
no, running .owl4ce var does not return anything because it is just a variable.

**Comment by WakanaYuki** [comment]
small update:
I have looked into the problem a bit more and it turns out reverting the autostart script back to the v2.1 fixes the whole startup problem. Problem is that the whole menu button/menu is broken sadly. It just displays a full screen gray-ish color.
Here a screenshot of the menu:

![2021-01-20-143242_1920x1080_scrot](https://user-images.githubusercontent.com/36765765/105181744-797f3300-5b2c-11eb-9c13-298a3175591c.png)

Luckily the right click context menu still works (I think it's called ob.. something?) with which I can get a console window with which I am trying the fix this stuff currently)
Here are some errors the v3.1 autostart script throws at me btw, maybe that can help you find out what's wrong.

`.config/openbox> ./autostart                                          
./autostart: 7: source: not found
bash: /mode-toggle: No such file or directory
./autostart: 15: [[: not found
./autostart: 18: [[: not found
./autostart: 28: [[: not found
./autostart: 24: [[: not found
./autostart: 21: [[: not found `

**Comment by owl4ce** [comment]
Strange, if autostart can't use the bash syntax.

**Comment by owl4ce** [comment]
I have an alternative, try to copy the `autostart` file to `autostart.sh`.
Then modify original file (autostart), only containing this

```bash
bash -c "~ / .config / openbox / autostart.sh"
```

**Comment by owl4ce** [comment]
Don't forget to make it executable.
`$ chmod +x autostart*`
![2021-01-20-204403_1366x768_scrot](https://user-images.githubusercontent.com/53987136/105183131-65edbf80-5b60-11eb-9e05-64ada4e92055.png)

**Comment by WakanaYuki** [comment]
I have found out, that the file was missing the file was missing the #!/bin/bash thing at the top. With that added, I don't get the weird errors. One thing though: the theme still doesn't start even with those addition and changes. So I still have to right click>Open Terminal>Start the autostart manually.
I will try your fix in a second and report back when done.

**Comment by owl4ce** [comment]
Yes, there must be a shebang for bash script.
Shebang is `#!/usr/bin/env bash`.

It indicates that the file is executed as bash. But actually openbox/autostart can be done without shebang.

**Comment by WakanaYuki** [comment]
that actually works. It autostarts now. Sadly the menu is still gray and the reboot/shutdow/etc. icons are missing, so a few things are still broken :/

**Comment by owl4ce** [comment]
> that actually works. It autostarts now. Sadly the menu is still gray and the reboot/shutdow/etc. icons are missing, so a few things are still broken :/

Any screenshots?

**Comment by owl4ce** [comment]
yeah, now my `la` is aliased with `exa`.

**Comment by WakanaYuki** [comment]
The menu:
screenshot from the first message today (the big gray screenshot)
Icons:
![2021-01-20-145816_1920x1080_scrot](https://user-images.githubusercontent.com/36765765/105184737-f9f36300-5b2f-11eb-8de9-0ea139c25f3c.png)

A few things are sadly still broken, all other icons, like from the screenshot menu are also not working :/

**Comment by owl4ce** [comment]
WOooaa, maybe it's rofi version. Here now only support rofi version `1.6.x`

**Comment by WakanaYuki** [comment]
When I run rofi it just displays this error message:
`Mode file-browser is not found`

**Comment by owl4ce** [comment]
This mode is only available in version `1.6.x`. You can turn it off here. I think Debian and Ubuntu are still stable on rofi version `1.5.4`, they haven't managed packages to `1.6.x`. The solution is manually compile [rofi](https://github.com/davatorium/rofi). https://github.com/owl4ce/dotfiles/issues/37
![2021-01-20-210733_581x540_scrot](https://user-images.githubusercontent.com/53987136/105185848-9d11a000-5b63-11eb-8b57-c22dee08f3c4.png)

**Comment by WakanaYuki** [comment]
Now it stucks while loading Openbox on the lockscreen. Welp.. I will look into it later or tomorrow a bit more :/

**Comment by owl4ce** [comment]
Whats your lockscreen?

**Comment by WakanaYuki** [comment]
I still have the usual Ubuntu/PopOS lockscreen. I think it's called unity, but don't quote me on that.

**Comment by owl4ce** [comment]
Are you experiencing screen glitching or flickering?

**Comment by WakanaYuki** [comment]
Not really, just that Openbox does not really starts correctly, I will try updating it and then compile rofi.
