### ISSUE TITLE
clicking on change wallpaper doesnt do anything [Bug]

### ISSUE THREAD

**Issue by sheeepdev** [owl4ce/dotfiles#44]
when i click anywhere in whatever menu to change my wallpaper, it doesn't do anything. i tried putting my wallpaper in ~/.wallpapers/mechanical but now its just a gray wallpaper, seems I have nitrogen installed but idk

**Comment by owl4ce** [comment]
Does this script work?
`./.config/openbox/visual-mode/wally`

![2021-01-29-143950_602x503_scrot](https://user-images.githubusercontent.com/53987136/106246012-04081680-6240-11eb-869a-50e8d12c5b03.png)

**Comment by sheeepdev** [comment]
oh! that works, but i was too wondering why don't the icons work ?

**Comment by owl4ce** [comment]
Btw, what terminal are you using?
Make sure it is defined in `~/.scripts/default/list`

![2021-01-29-144747_1155x435_scrot](https://user-images.githubusercontent.com/53987136/106246686-120a6700-6241-11eb-9874-e3d9f3a11a9c.png)

**Comment by sheeepdev** [comment]
(the icons for changing the wallpaper (right-click > theme styling > change the wallpaper and the mountain icon on for changing wall)

**Comment by sheeepdev** [comment]
I use hyper, its defined in ~/.scripts/default list, terminal="hyper"

**Comment by owl4ce** [comment]
try this, does it work?
`./.scripts/default-apps/launch terminal -e ~/.config/openbox/visual-mode/wally`

It will bring up a terminal and then execute wally

![2021-01-29-144955_655x443_scrot](https://user-images.githubusercontent.com/53987136/106246873-60b80100-6241-11eb-9efa-bbdfeaa31ebd.png)

**Comment by sheeepdev** [comment]
yeah i said that works, but the icons on right click menu and left menu dont

**Comment by sheeepdev** [comment]
wait a second.. it doesnt work...

**Comment by sheeepdev** [comment]
Is something wrong with my terminal then ?

**Comment by sheeepdev** [comment]
but its wierd that the button style script opens a terminal and it works ?

**Comment by owl4ce** [comment]
wait a moment

**Comment by owl4ce** [comment]
Button change wallpaper from tint2 not working? but run from the terminal works?
Oddly changing button style works on tint2?

**Comment by sheeepdev** [comment]
Yeah button style works and change wallpaper doesn't, it probably tries to launch hyper but fails, I really don't have and idea how button style works

**Comment by owl4ce** [comment]
No-no it both opens a defined terminal. Well sadly, I didn't find any problems at all :)

![2021-01-29-151008_1183x372_scrot](https://user-images.githubusercontent.com/53987136/106248864-2ef46980-6244-11eb-8e40-70d6992c0d2c.png)

**Comment by owl4ce** [comment]
Yeah, even though hyper is very sophisticated for programming. I don't know where the problem is, I wonder.

**Comment by sheeepdev** [comment]
also the picture on neofetch flickers a bit and disappears on hyper

**Comment by owl4ce** [comment]
Yeahh :)
![Screenshot_20210129-210254-picsay](https://user-images.githubusercontent.com/53987136/106284222-83fca380-6275-11eb-960f-f2985703b876.png)
