### ISSUE TITLE
The Wi-fi connection information is not displayed in the Minimal-mode panel

### ISSUE THREAD

**Issue by maccree** [owl4ce/dotfiles#46]
Hi, I noticed this a long time ago, and on different computers, for some reason it always writes "Disconnected" although there is wi-fi. In older versions of dotfiles, there was no such problem

( Arch x86_64 | 5.10.13-arch1-1  )

![image](https://user-images.githubusercontent.com/36086205/107130367-a463d800-68dd-11eb-90f9-5cee86080e1f.png)

**Comment by owl4ce** [comment]
Have you installed [wireless_tools](https://archlinux.org/packages/core/x86_64/wireless_tools/)?
and define the interface here. You can check the interface name with `ip link` or `ifconfig`.
https://github.com/owl4ce/dotfiles/blob/92e22b84d3e278a393b0eee358c048bfe85cee50/.owl4ce_var#L95-L102

**Comment by maccree** [comment]
thank you and I apologize for a very stupid question
