### ISSUE TITLE
Make for xfwm4 dot themes 

### ISSUE THREAD

**Issue by skydie22** [owl4ce/dotfiles#47]
hallo , your theme is amazing . pliss make for xfwm4 themes , pliss

**Comment by owl4ce** [comment]
**Hi @skydie22** 
Sorry right now it is stuck on openbox, haven't had time or don't have the imagination to go to another WM.
I have tried several other WM but I am not suitable, so I dropped it.

**Another alternative:**
- [addy-dclxvi/xfwm4-theme-collections](https://github.com/addy-dclxvi/xfwm4-theme-collections)
- [Nztux/fuut-xfwm.xfce-theme-Collections](https://github.com/Nztux/fuut-xfwm.xfce-theme-Collections)
