### ISSUE TITLE
Doom Emacs not opening

### ISSUE THREAD

**Issue by Azenyte** [owl4ce/dotfiles#48]
OS: Ubuntu 20.04
I tried setting urvxt to transparent and it would not load emacs. Tried it in the terminal and it would output "Undefined color: [90]#F9F9F9 or [90]#373E4D. Any ideas on how to fix this? 

Edit: Tried it with emacs(Terminal) and it works fine, but its not working with emacs(GUI)

**Comment by owl4ce** [comment]
**Hi @Azenyte** 
I am not sure what the problem is, as I have never used doom emacs.

**Comment by owl4ce** [comment]
Is this problem related to urxvt with transparency and not using transparency?

**Comment by Azenyte** [comment]
Yes the emacs(GUI) seems to not recognized the colors when setting urvxt to transparent. I tried urvxt without transparency and emac(GUI) works fine.
