### ISSUE TITLE
Icon error

### ISSUE THREAD

**Issue by tuilakhanh** [owl4ce/dotfiles#49]
**Describe the bug**
Icon error 

**Screenshots**

![alt text](https://media.discordapp.net/attachments/737981119630409820/808022383776628746/2021-02-08-000840_1366x768_scrot.png)

![alt text](https://media.discordapp.net/attachments/737981119630409820/808022389010071582/2021-02-08-000910_1366x768_scrot.png)

**Desktop:**
 - **OS**: Arch Linux

**Comment by owl4ce** [comment]
https://github.com/owl4ce/dotfiles/issues/37

**Comment by owl4ce** [comment]
I think it's just a matter of fonts, is there already `Feather.ttf` in `~/.fonts`?
Btw, if the problem with the rofi version can be seen at https://github.com/owl4ce/dotfiles/issues/37.

**Comment by tuilakhanh** [comment]
The font is here and the rofi version is 1.6.1.
![Uploading image.png…]()
I think my device displays wrong font. How can i change the font?

**Comment by tuilakhanh** [comment]
I think my problem got solved by moving my font pack from '/usr/share/font' to '~. / font'

**Comment by tuilakhanh** [comment]
The font make this error is UVF Champion Script Pro when I delete this font, it works normally
