### ISSUE TITLE
[SLiM] OpenBox instance disappears if you switch ttys

### ISSUE THREAD

**Issue by HopeBaron** [owl4ce/dotfiles#5]
Issue:
When you switch ttys and get back to your OB interface the session will suddenly be hidden (still running in background tho)

Reproduce: 
1. Login to your OB through SLiM
2. Switch to any other tty (ALT + CTRL + Fn)
3. Switch back to tty1 or whatever tty your OB runs on
There you go. Your session is still there, but it disappeared

Notes: 
- This doesn't happen with `startx`
- You have to do `killall -u username` in order to run a fresh session else you will have troubles launching some programs like redshift or Discord

Suggestions:
- Switch back to another display manager 
- Find a workaround (which I didn't find yet)

**Comment by owl4ce** [comment]
Sorry, but I have no such problem. I also occasionally open tty1 and go back to slim session on tty7 and nothing happens. actually using slim is optional on my dotfiles, not required.
