### ISSUE TITLE
Terminal look weird now [Bug]

### ISSUE THREAD

**Issue by linuxmobile** [owl4ce/dotfiles#53]
**Describe the bug**
Hi, i decide to install again from zero, but now terminal look weird..

**Expected behavior**
Termite work fine, but urxvt work weird

**Screenshots**
![2021-02-14-020716_581x349_scrot](https://user-images.githubusercontent.com/10554636/107866480-6597ca00-6e69-11eb-8cf4-05ad13064516.png)

**Desktop (please complete the following information):**
 - **OS**: 
 Arch Linux x86_64 
 5.10.16-arch1-1

**Comment by owl4ce** [comment]
**Hi @linuxmobile** 
I'm not sure what the problem is, have you set the [locale](https://wiki.archlinux.org/index.php/locale)?

**Comment by linuxmobile** [comment]
> **Hi @linuxmobile**
> I'm not sure what the problem is, have you set the [locale](https://wiki.archlinux.org/index.php/locale)?
> Also try installing with the different urxvt packages, `rxvt-unicode-patched` and `rxvt-unicode`. Is there a difference?
> 
> If the font is too wide it is possible to handle it, simply unmark this line.
> 
> https://github.com/owl4ce/dotfiles/blob/6747c111d79801d6c74f80cc342df368fa10594c/.Xresources#L18-L19
> 
> By the way, does it happen when opening `urxvt` or when typing a character?

Yes, i've set locale... I already try with other packages from urxvt but not working anything... 

**And it's happen when u open urxvt.**

Termite work proper: 
![2021-02-14-111126_604x336_scrot](https://user-images.githubusercontent.com/10554636/107875025-69513e00-6eb5-11eb-99d8-20c721e79ae6.png)

**Comment by owl4ce** [comment]
**@linuxmobile**
Let me know, does this fix this issue?
https://github.com/owl4ce/dotfiles/commit/d25de6c7b031dcf327c9bf5bff0d58c59614db96#diff-76ca8b85960fd14348e9caa3ebabe00c3cf21593a94036f4ba3305c262809a34L4-R4

**Comment by ledleledle** [comment]
@owl4ce unfortunately it does not fix the issue. but maybe this issue its just because of an unsupported font

![2021-02-18-034346_469x128_scrot](https://user-images.githubusercontent.com/47093803/108265611-98103280-719b-11eb-884c-5502d86c6ecd.png)

here the result
![2021-02-18-034609_582x129_scrot](https://user-images.githubusercontent.com/47093803/108265824-e1608200-719b-11eb-9650-0a15ff509c76.png)

https://github.com/owl4ce/dotfiles/commit/a55e311cb0781fea80fa67dfbd6917bfc390487b
https://github.com/owl4ce/dotfiles/commit/ac14f750e9eeecff4d36380d4b49f3f07714e39e

**Comment by owl4ce** [comment]
> @owl4ce unfortunately it does not fix the issue. but maybe this issue its just because of an unsupported font
> 
> ![2021-02-18-034346_469x128_scrot](https://user-images.githubusercontent.com/47093803/108265611-98103280-719b-11eb-884c-5502d86c6ecd.png)
> 
> here the result
> ![2021-02-18-034609_582x129_scrot](https://user-images.githubusercontent.com/47093803/108265824-e1608200-719b-11eb-9650-0a15ff509c76.png)
> 
> [a55e311](https://github.com/owl4ce/dotfiles/commit/a55e311cb0781fea80fa67dfbd6917bfc390487b)
> [ac14f75](https://github.com/owl4ce/dotfiles/commit/ac14f750e9eeecff4d36380d4b49f3f07714e39e)

Okay, I forgot about special char. My fault, thanks for reminding.
