### ISSUE TITLE
xfce-power-manager tray showing black icon

### ISSUE THREAD

**Issue by ledleledle** [owl4ce/dotfiles#56]
hey... i love you dotfiles a lot and i used it since version 2. at version 2 the battery icon the color changes when the theme is changed and system tray is restarted. now i tried restarting the tray, but still no luck.

![Peek 2021-02-18 20-21](https://user-images.githubusercontent.com/47093803/108363727-d5ba9d00-7227-11eb-841d-dd70cb9d79a2.gif)

**Comment by owl4ce** [comment]
**Hi @ledleledle**
Sorry, I'm not using a battery so far so I'm not using a power-manager. I'll check the icon later.

**Comment by owl4ce** [comment]
I know, maybe because `xfce4-power-manager` is on openbox/autostart should be in the tray. Can you try it? @ledleledle

**Comment by ledleledle** [comment]
@owl4ce it worked. but its that normal to have black icon in dark mode?

**Comment by owl4ce** [comment]
> @owl4ce it worked. but its that normal to have black icon in dark mode?

Idk, I'll check and update the Papirus-Dark-Custom icons.

**Comment by owl4ce** [comment]
Hi I have checked, you can also check in different sizes dir. It's not black at all.

![image](https://user-images.githubusercontent.com/53987136/108456316-9da47000-72a2-11eb-985a-e43470a7079f.png)
