### ISSUE TITLE
i need little help!

### ISSUE THREAD

**Issue by ertoorule** [owl4ce/dotfiles#6]
wifi is connected but panel shows disconeted how can i fix it!
<a href="https://imgbb.com/"><img src="https://i.ibb.co/3TJ7f7d/2020-09-10-220259-407x35-scrot.png" alt="2020-09-10-220259-407x35-scrot" border="0"></a>

**Comment by owl4ce** [comment]
have you adjusted the wifi interface?

_~/.config/tint2/executor/network_
---
...

intwifi="wlan0"
intether="eth0"

...

how to check:
**ifconfig** or **ip addr**

**Comment by ertoorule** [comment]
> have you adjusted the wifi interface?
> ## _~/.config/tint2/executor/network_
> 
> ...
> 
> intwifi="wlan0"
> intether="eth0"
> 
> ...
> 
> how to check network interface:
> **ifconfig** or **ip addr**

Than you so much!
