### ISSUE TITLE
Ncmpcpp album art script don't work (i have all the necessary dependencies)

### ISSUE THREAD

**Issue by hrqmonteiro** [owl4ce/dotfiles#65]
**Describe the bug**
The album art won't show.

**Expected behavior**
The album art to show..

**Screenshots**
![2021-03-07_20-57](https://user-images.githubusercontent.com/17055027/110259696-d7a29100-7f87-11eb-8131-2ed5b3de914b.png)

**Desktop (please complete the following information):**
 - **OS**:  Void Linux

**Comment by hrqmonteiro** [comment]
Update: after playing with it for two hours, i was able to make it work but it has a black square. Can i fix it?

![2021-03-07_22-53](https://user-images.githubusercontent.com/17055027/110264372-eee97a80-7f97-11eb-9030-d183eeeb6f6b.png)

(And i still don't know why the Nerd Font icons are not showing on Urxvt..

**Comment by owl4ce** [comment]
> Update: after playing with it for two hours, i was able to make it work but it has a black square. Can i fix it?
> 
> ![2021-03-07_22-53](https://user-images.githubusercontent.com/17055027/110264372-eee97a80-7f97-11eb-9030-d183eeeb6f6b.png)
> 
> (And i still don't know why the Nerd Font icons are not showing on Urxvt..

Do you use depth 32 on `~/.Xresources`? if yes pixbuf does turn black in the background.

One of the reasons why I use the w3m backend is for the terminal transparency to work with images, not for pixbuf.
The problem is in the depth of 32. Change it to 24.

**Comment by owl4ce** [comment]
For glyphs, it might be a letterspace issue
