### ISSUE TITLE
Missing xor-xwininfo dependency

### ISSUE THREAD

**Issue by negativeExponent** [owl4ce/dotfiles#66]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - **OS**: [e.g. Arch Linux]

**Additional context**

Just something minor, missing xorg-xwininfo required for ncmpcpp alburm art modes (of some kind)

**Comment by owl4ce** [comment]
**Hi @negativeExponent** 
Thank you for reminding, I will add it to read me.
