### ISSUE TITLE
Start button character is in wierd color [Bug]

### ISSUE THREAD

**Issue by sheeepdev** [owl4ce/dotfiles#73]
So, basically, i configured my start button to this moon with clouds (it was an example in the file)

now, the character's color is really wierd, as its the background color

![image](https://user-images.githubusercontent.com/68562536/112731365-08e30100-8f37-11eb-9aa6-8ceff35494ca.png)

**Comment by sheeepdev** [comment]
I want it to be white and not black / gray

**Comment by owl4ce** [comment]
Can you send full screenshots? This happened to Mechanical / Eyecandy?

`STARTCOLOR1` and `STARTCOLOR2` should change when the UI is restarted.
![image](https://user-images.githubusercontent.com/53987136/112731560-ac013e00-8f6a-11eb-8a81-9febe0050853.png)

**Comment by owl4ce** [comment]
**UI started**
  1. STARTCOLOR -> hex (var)
  2. **Run panel**
  3. hex -> STARTCOLOR

If panel killed by switching modes/ restart ui, number 3 started.

**Comment by sheeepdev** [comment]
Can you tell me exactly what do you mean, i dont understand u

**Comment by owl4ce** [comment]
I am just talking about the flow of how the color can change from a variable.

**Comment by sheeepdev** [comment]
Yeah but i still dont understand how to change the color

**Comment by owl4ce** [comment]
This happened to Mechanical / Eyecandy?

**Comment by sheeepdev** [comment]
mechanical

**Comment by sheeepdev** [comment]
While changing variables i wanted the background of the start button to be that color, which it did, but it broke the button (emoji or whatever)

**Comment by owl4ce** [comment]
Can you send me a full screenshot? regarding your variable and the problematic tint2 ..
and try copying the tint2 configuration again from this repo.

_I really didn't have any problems with my configuration._

**Comment by sheeepdev** [comment]
Im not sure you understand me, bascally, i changed some vars in .owl4ce.var and the start button background changed, which i wanted, BUT the icon inside the start menu (the emoji) is in this wierd color

**Comment by sheeepdev** [comment]
FOUND IT! # Button 1 in tint2rc line 285

**Comment by owl4ce** [comment]
Oh sorry, can you match this configuration to yours?

https://github.com/owl4ce/dotfiles/blob/a8f3099238f4e234cf6b60a691b3cf113bd1670d/.config/tint2/mechanical-vertical.tint2rc#L284-L300

and

https://github.com/owl4ce/dotfiles/blob/a8f3099238f4e234cf6b60a691b3cf113bd1670d/.config/tint2/mechanical-horizontal.tint2rc#L293-L309

**Comment by sheeepdev** [comment]
Yeah did that works perfectly now :)

**Comment by sheeepdev** [comment]
Dont know how it defaulted to that color in the first place 🤔 

But now it looks like it should 🤷🏻

**Comment by owl4ce** [comment]
Good work! 😸

**Comment by sheeepdev** [comment]
ty :) Thanks for trying to help out :D
