### ISSUE TITLE
Scroll keybind on desktop

### ISSUE THREAD

**Issue by sheeepdev** [owl4ce/dotfiles#75]
Hi owl4ce!

First up your dotfiles amazing

but i just have one problem, since I dont really use workspaces, i sometimes accidentally scroll on the desktop and it takes me to a new workspace, is there any way to remove this keybind?

**Comment by sheeepdev** [comment]
🤔

**Comment by owl4ce** [comment]
wait

**Comment by owl4ce** [comment]
Here is it
https://github.com/owl4ce/dotfiles/blob/48f0d337ba3fb275f909c8c64cb456fefccecd32/.config/openbox/rc.xml#L710-L719

Change to

```xml
      <!-- <mousebind button="Up" action="Click">
        <action name="GoToDesktop">
          <to>previous</to>
        </action>
      </mousebind>
      <mousebind button="Down" action="Click">
        <action name="GoToDesktop">
          <to>next</to>
        </action>
      </mousebind> -->
```

Then

```zsh
$ openbox --reconfigure
```

or by pressing <kbd>Super</kbd> ➜ <kbd>Shift</kbd> ➜ <kbd>R</kbd>

**Comment by sheeepdev** [comment]
Thanks!
