### ISSUE TITLE
Rofi font bug 

### ISSUE THREAD

**Issue by Maximumtix** [owl4ce/dotfiles#78]
I copied the fonts file from a Windows 7 installation i had, as described in Arch
Wiki.(https://wiki.archlinux.org/index.php/Microsoft_fonts) But doing so breaks the all rofi menu fonts. I deleted the WindowsFonts file and reset the font cache and it fixed the issue. But I can't see what is causing the issue.

![2021-03-30_15-44](https://user-images.githubusercontent.com/70814372/112990966-4fbb3b80-916f-11eb-8c22-078e94869b76.png)
![2021-03-30_15-46](https://user-images.githubusercontent.com/70814372/112990995-5649b300-916f-11eb-81a6-82af095475a7.png)

Edit: Uploaded the wrong screenshots
Distro = Artix Linux-Runit

**Comment by owl4ce** [comment]
> ** (process:26632): WARNING **: 15:19:13.737: /home/maximumtix/.config/rofi/config.rasi:11:31: Option: display-calc is not found. is the only error i can find.
> By the way resetting fonts are not required to reproduce this issue. Just moving the file to /usr/share/fonts/ or removing it from there is enough to trigger the bug.
> 
> Rofi version: 1.6.1

Ignore `display-calc` as it's not a serious problem, it's just that I'm providing glyphs for the user [`rofi-calc`](https://github.com/svenstaro/rofi-calc). 

Are the font glyphs still colliding? I found the problem, but I haven't had enough time to fix all of them.

**Comment by owl4ce** [comment]
Maybe I will fix this issue in this week.

**Comment by owl4ce** [comment]
In the case of 5 vertical menu options, the key is

https://github.com/owl4ce/dotfiles/blob/3517d91629a3b16b404e3a7604ddbf58b5ec96f4/.config/rofi/themes/sidebar/five-vertical.rasi#L6
https://github.com/owl4ce/dotfiles/blob/3517d91629a3b16b404e3a7604ddbf58b5ec96f4/.config/rofi/themes/sidebar/five-vertical.rasi#L10
https://github.com/owl4ce/dotfiles/blob/3517d91629a3b16b404e3a7604ddbf58b5ec96f4/.config/rofi/themes/sidebar/five-vertical.rasi#L50

It should look like this
```cfg
6    icon-font:                            "feather 18";

10   menu-element-padding:                 20px 0px 17px 3px;

50   font: @icon-font;
```

Give it a try, does that fix this issue?

**Comment by Maximumtix** [comment]
Made it worse. :(

![2021-03-30_16-16](https://user-images.githubusercontent.com/70814372/112994975-70859000-9173-11eb-9f52-f0674f423944.png)

**Comment by owl4ce** [comment]
Idk why, but it worked for me
![2021-03-31-093428_1366x768_scrot](https://user-images.githubusercontent.com/53987136/113082366-85f6ca80-9204-11eb-968a-154d7d926c2a.png)

**Comment by Maximumtix** [comment]
Oh I forget to tell my screen resolution : 1366x768. Same as yours I believe.

Done some experimentation on it. Moving the "WindowsFonts" file to local fonts directory didn't help.
Not a single font size works with the setting `font=@text-font;` . 
So I changed it to `font=@icon-font;` like you said. And  `icon-font:                            "feather 18";` does not work but ANY font size below 18 is fine. Therefore I chose "17". 
`menu-element-padding:                 20px 0px 17px 3px;` looks great on horizontal sidebars but for vertical sidebars i recommend `menu-element-padding:                 20px 0px 17px 2px;` It is the closest to being perfectly symmetrical. Trust me i have done measurements on my screen with a ruler. :laughing: 

Now can you tell what are the elements i have to change in order fix https://github.com/owl4ce/dotfiles/blob/main/.config/rofi/themes/appsmenu.rasi 
https://github.com/owl4ce/dotfiles/blob/main/.config/rofi/themes/networkmenu.rasi
https://github.com/owl4ce/dotfiles/blob/main/.config/rofi/themes/promptmenu.rasi
![2021-04-01_02-36](https://user-images.githubusercontent.com/70814372/113224413-0d3f4f00-9294-11eb-99bb-29c9f623129d.png)
![2021-04-01_02-36_1](https://user-images.githubusercontent.com/70814372/113224415-103a3f80-9294-11eb-833b-1bfcf5a4da7e.png)

**Comment by Maximumtix** [comment]
Works like a charm thanks! I used plain "feather" instead of "feather Bold". Blends in better with Comfortaa fonts. 
I think this is the last icon that has the same problem.
![2021-04-01_11-30](https://user-images.githubusercontent.com/70814372/113269836-87e28b80-92e1-11eb-9f9b-cf8e7b1df752.png)
I will send a PR after you tell me the solution of this.

**Comment by owl4ce** [comment]
> Works like a charm thanks! I used plain "feather" instead of "feather Bold". Blends in better with Comfortaa fonts.
> I think this is the last icon that has the same problem.
> ![feather](https://user-images.githubusercontent.com/70814372/113271480-405cff00-92e3-11eb-80a0-27e165113bb9.png)
> I will send a PR after you tell me the solution of this.
> Edit: feather Bold vs feather

Only happens in `file-browser` modi?

**Comment by Maximumtix** [comment]
> Only happens in `file-browser` modi?
Yes, that's right.

**Comment by owl4ce** [comment]
**@Maximumtix** 
Sorry. I don't know, it should be included in the resolution configuration. If it bothers you, just turn off the `file-browser` modi or change the glyphs.

https://github.com/owl4ce/dotfiles/blob/89feca2212b490fdef7996cf05c2c9b197de8828/.config/rofi/themes/shared/resolutions/1366x768.rasi#L4

here
https://github.com/owl4ce/dotfiles/blob/90cd4690bc3813b3552970b360b8daa65d9261fc/.config/rofi/config.rasi#L1-L14

**Comment by Maximumtix** [comment]
#80  
Material Font Folder glyph doesn't work for some reason so I replaced it with feather Font folder glyph. Its insides are not filled but looks really fitting.
![2021-04-02_18-30](https://user-images.githubusercontent.com/70814372/113429687-9f08a280-93e1-11eb-8e61-8ec79fa57f67.png)
