### ISSUE TITLE
Rofi fullscreen search

### ISSUE THREAD

**Issue by sheeepdev** [owl4ce/dotfiles#79]
Hi, its me again. Im opening too many issues here, sorry lol

anyways,

let me explain

So when you click on the main icon (first one) (the start menu) it opens a fullscreen rofi menu. How can I make it launch a normal rofi window with a theme I downloaded?

Again sorry for opening issues here but these dots are so amazing and customizable that i have so many questions

**Comment by sheeepdev** [comment]
Sorry, im fucking stupid. I needed to change one line in the tint2 thing.

**Comment by owl4ce** [comment]
**@sheeepdev** 
Just relax, if you have questions, please go to the [discussion](https://github.com/owl4ce/dotfiles/discussions).

**Comment by sheeepdev** [comment]
Didnt even know that discussion existed, sorry lmao

if i have any more questions ill go there
