### ISSUE TITLE
amixer has `-q/--quiet` flag to suppress output

### ISSUE THREAD

**Issue by murlakatamenka** [owl4ce/dotfiles#8]
Just a small notice that you can make a tad cleaner https://github.com/owl4ce/dotfiles/blob/master/.scripts/notify/change-volume

```sh
amixer -D pulse sset Master 5%+ > /dev/null
```
=
```sh
amixer -D pulse sset Master 5%+ -q
```
=
```sh
amixer -D pulse sset Master 5%+ --quiet
```
Can be a matter of choice, of course. Anyway, awesome setup, thanks for sharing :heart:

**Comment by owl4ce** [comment]
Thank you very much, I paid less attention. Apparently it can also be for `brightnessctl`
