### ISSUE TITLE
Brightness Handler not working [Bug]

### ISSUE THREAD

**Issue by KisaragiRintarou** [owl4ce/dotfiles#85]
**Describe the bug**
I can't control the brightness when i use the function key or the 3-button menu it will show the brightness level (which mean the notify does works) but the brightness won't change

**Expected behavior**
Well i expect the brightness menu button to work

**Desktop**
 - **OS**: Xubuntu 20.04

**Comment by Maximumtix** [comment]
Do you have brightnessctl installed?

**Comment by KisaragiRintarou** [comment]
yes i did if i didn't it will ask me to install brightnessctl

**Comment by owl4ce** [comment]
> yes i did if i didn't it will ask me to install brightnessctl

Have you done this step?

![image](https://user-images.githubusercontent.com/53987136/114654112-a9953700-9d13-11eb-9c59-5197feb3a11a.png)

`$ sudo chmod u+s $(command -v brightnessctl)`

**Comment by KisaragiRintarou** [comment]
giving brightnessctl root privilege fixed it thank you!!!!
