### ISSUE TITLE
Make screenshot saving optional [Feature Req]

### ISSUE THREAD

**Issue by FlyingCat-X** [owl4ce/dotfiles#88]
**Is your feature request related to a problem? Please describe.**
It's somewhat uncomfortable to be deleting my Screenshots folder from time to time.

**Describe the solution you'd like**
A new variable in `.owl4ce_var` that will be used to make screenshot saving optional.
Something like:
`SAVE_SCREENSHOT="yes/no"`

**Describe alternatives you've considered**
I considered using another application like flameshot but didn't like it as much.
Also, I thought maybe I could do it if I commented `SAVE_DIR` but if I do that it saves to `/home/my_user`.

**Additional context**
None.

**Comment by owl4ce** [comment]
Good idea

**Comment by owl4ce** [comment]
**@FlyingCat-X** 
Do you mean using clipboard instead of saving to `SAVE_DIR`?

**Comment by FlyingCat-X** [comment]
If `SAVE_SCREENSHOT` (or whatever it will be called) is `yes` then it would be stored in the clipboard and at the same time saved in "SAVE_DIR" (As the script currently works), if `no` then it would only be stored in the clipboard and not saved in "SAVE_DIR".

It would also be great if fullscreen screenshots were also stored in the clipboard. but idk if it's correct to put it here or in a new issue.

_PS: Sorry for my bad english, english is not my native language ;-;_

**Comment by owl4ce** [comment]
> If `SAVE_SCREENSHOT` (or whatever it will be called) is `yes` then it would be stored in the clipboard and at the same time saved in "SAVE_DIR" (As the script currently works), if `no` then it would only be stored in the clipboard and not saved in "SAVE_DIR".
> 
> It would also be great if fullscreen screenshots were also stored in the clipboard. but idk if it's correct to put it here or in a new issue.
> 
> _PS: Sorry for my bad english, english is not my native language ;-;_

Ok, agreed.

**Comment by owl4ce** [comment]
Done in https://github.com/owl4ce/dotfiles/commit/32ddab1d3513d6308be1fe91c667f887d078ee3b.

**Comment by FlyingCat-X** [comment]
Thank you!
