### ISSUE TITLE
Window Buttons broken

### ISSUE THREAD

**Issue by PersonaAshley** [owl4ce/dotfiles#9]
Heya, I've been loving and using this theme for weeks now until I reinstalled Arch and for some reason the buttons are broken.
![2020-09-25-210324_420x236_scrot](https://user-images.githubusercontent.com/66917776/94309099-d4868c00-ff77-11ea-8242-5abf71211a2d.png)

Any ideas on how to fix this?
This is on the newest version of Openbox

**Comment by owl4ce** [comment]
if you followed the setup, it should work normally

**The minimum font size for window title is 10**
![2020-09-26-033414_520x96_scrot-framed](https://user-images.githubusercontent.com/53987136/94313586-2d224d00-ffa9-11ea-8229-5ea435dc0691.png)

**Comment by owl4ce** [comment]
**Was it resolved?** When finished I will close the issue.

**Comment by PersonaVinny** [comment]
It was already set to 10 
![2020-09-26-132933_420x236_scrot](https://user-images.githubusercontent.com/66917776/94339729-69cb6400-fffc-11ea-9f58-99945cd70788.png)

**Comment by owl4ce** [comment]
I don't know what to do with your problem. Still confused where the mistake.

**Comment by PersonaVinny** [comment]
Hmm,
I'm gonna try to set some more things maybe start from scratch or something, maybe that will help
I'll keep you posted!

**Comment by WakanaYuki** [comment]
I had the same problem. Setting the Font Size from 10 to 15 fixed it for me

**Comment by owl4ce** [comment]
> I had the same problem. Setting the Font Size from 10 to 15 fixed it for me

What is your Linux distro? And what is your resolution and dpi?

**Comment by WakanaYuki** [comment]
I am on Pop-OS and have a resolution of 2560x1440. I honestly have no idea where I can find out my dpi.. I looked in the nvidia x server settings but didn't find anything.
The only problem I have is that screen is 144hz. And Firefox and most other applications just run on 60hz, which makes my monitor weirdly blink a few shades darker than the actual image on the edges. Not annoyingly, just eye strainingly.

**Comment by owl4ce** [comment]
@WakanaYuki 
Can you please send us screenshots, TBH my resolution is only 1366x768 so I can't fix it if there are problems with high resolution and dpi. I really want to see this theme at high resolution :)

**Comment by WakanaYuki** [comment]
![Screenshot from 2020-10-10 13-18-34](https://user-images.githubusercontent.com/36765765/95653756-5c819f80-0afb-11eb-963c-fbbf93320da1.png)
![Screenshot from 2020-10-10 13-19-08](https://user-images.githubusercontent.com/36765765/95653757-5db2cc80-0afb-11eb-9f9b-410688e75b89.png)
Like this? @owl4ce 
Note: I have a 1440p and a 1080p monitor, so thats why the background looks so cut of and a bit off.

**Comment by owl4ce** [comment]
![2020-10-10-182408_47x154_scrot-framed](https://user-images.githubusercontent.com/53987136/95653845-d3cc2900-0b25-11eb-8903-666f673a57df.png)

What happened to wifi icon? the color is pink as in the eyecandy theme.

**Comment by WakanaYuki** [comment]
Honestly I don't know, but I don't really mind that, tbh.

**Comment by hamadmarri** [comment]
This only happens to me when I restart openbox. I already have xrandr --dpi 144

It could be the reason why.

**Comment by owl4ce** [comment]
I have tried changing to dpi 144 then restarting openbox, but it is working normally.
![2021-01-14-194646_1920x1080_scrot](https://user-images.githubusercontent.com/53987136/104592845-6e964f80-56a1-11eb-9764-07e0f48f3c70.png)
