### ISSUE TITLE
[Discord/BetterDiscord] Side panel is not skinned [Bug]

### ISSUE THREAD

**Issue by FlyingCat-X** [owl4ce/dotfiles#90]
**Describe the bug**
The side panel with the servers doesn't have the same color as the rest of the app.
I'm not sure if this happened with previous versions of BetterDiscord.

**Expected behavior**
The side panel should have the same color as the rest of the app.

**Desktop (please complete the following information):**
 - **OS**: Arch Linux 5.11.14-zen1-1-zen
 - **Discord version**: 0.0.14-1
 - **BetterDiscord version**: idk exactly what version it's but I used the new cross-platform installer, downloaded from [here](https://github.com/BetterDiscord/Installer/releases).

**Additional context**
I'm not sure if this is the right way to do it but I managed to make it look good by adding this at the bottom:
- sweety-discord-light.css file:
```css
.theme-dark {
    --background-tertiary: #F9F9F9;
    --background-secondary: #F9F9F9;
}
```
The color of `--background-tertiary` and `--background-secondary` are the same as `--backgroundDark`.
I did the same with the other theme.

**Screenshots**
- Before
![](https://media.discordapp.net/attachments/773021896979644446/833130749012082698/unknown.png?width=705&height=407)

- After
![](https://media.discordapp.net/attachments/773021896979644446/833131001432506379/unknown.png?width=705&height=407)

**Comment by owl4ce** [comment]
**@pr1nce55**

**Comment by pr1nce55** [comment]
Try deleting .config/BetterDiscord and installing betterdiscord from here -> https://github.com/rauenzi/BetterDiscordApp

**Comment by FlyingCat-X** [comment]
Now I tried with that installer and it's still the same
![image](https://user-images.githubusercontent.com/33896771/115149210-ab6b3d00-a028-11eb-8c7d-68948298bad9.png)
