### ISSUE TITLE
Task with emojis in the name have a wierd symbol in the circle [Bug]

### ISSUE THREAD

**Issue by sheeepdev** [owl4ce/dotfiles#94]
On the task list thing when there's an app running with an emoji (from what i understood) it puts this wierd symbol in the circle, how can i fix this?
![image](https://user-images.githubusercontent.com/68562536/116273760-5646ce00-a782-11eb-9192-3e66421d671a.png)

**Comment by sheeepdev** [comment]
Sorry if i explained this wrong lol

**Comment by owl4ce** [comment]
Hmm, I still don't knows about that and how to solve.

**Comment by sheeepdev** [comment]
Hmm this really bothers me idk how you'll solve this

**Comment by owl4ce** [comment]
> Hmm this really bothers me idk how you'll solve this

Did you install `noto-emoji`?

**Comment by sheeepdev** [comment]
Installed just now. Still the same.

**Comment by owl4ce** [comment]
Yeah, same here. This is unresolved issue.

![image](https://user-images.githubusercontent.com/53987136/116812887-57f60480-ab7b-11eb-8e0b-6d6dc80e2773.png)
