### ISSUE TITLE
App Launcher Empty [Bug]

### ISSUE THREAD

**Issue by bweeirl** [owl4ce/dotfiles#96]
Hello, I recently started ricing, and decided to give your dotfiles my first go. It's great so far. I went through every step and the installation was sucessful However, there are some kinks I still need to work out like empty app launcher. As I don't know whats causing this, I'm currently using the right click menu to launch apps at this time. I posted a .gif below for you to see whats exactly going on here.

Distro: Linux Mint 20.1 (Cinnamon)
Kernal: x86_64 Linux 5.4.0-58-generic
CPU: AMD Ryzen 5 4600H
GPU: GeForce GTX 1650 Ti

![screencapture](https://user-images.githubusercontent.com/77660849/116791318-acfc2280-aa76-11eb-91bd-e299e0145e8d.gif)

**Comment by owl4ce** [comment]
Hello @bweeirl 
Umm, maybe its rofi version. What's version of the rofi? its should be above `1.6.x`.
Another issue: https://github.com/owl4ce/dotfiles/issues/37

Also,
can you check `~/.config/rofi/themes/shared/colorschemes` ?
Its should be `fullscreen` if you using `eyecandy` theme.
https://github.com/owl4ce/dotfiles/blob/cc02b9df80a0a9b40d2aa1851ab23f0edc098b7f/.config/rofi/themes/shared/settings.rasi#L1-L11

**Comment by bweeirl** [comment]
Hey!
Sorry for the late response. I just decided to move everything to Arch and everything's working fine there. Thanks for the help though!
