### ISSUE TITLE
problems with the work of configs ubuntu 20.04

### ISSUE THREAD

**Issue by xxxvik-xakerxxx** [owl4ce/dotfiles#97]
I have been using your configs for a long time this is a great config but there are a couple of problems that I face every day
1 when the user is logged in, the entire interface does not work until I manually restart the interface in the openox menu or select 1 of the presets
2 auto blocking does not work after a while
3 if I close the laptop, it goes into sleep mode, but when I open it and immediately get into the interface, the same thing happens when I manually put the laptop into sleep mode
I understand that most likely this is a problem purely for me and my system, but maybe it can be somehow solved

**Comment by owl4ce** [comment]
**number 1,**
What about the startup appearance? Is it just a black (or gray) blank and no panels appear?

**number 2,**
What does auto blocking mean?

**number 3,**
Sorry, I rarely sleep on my laptop, but isn't that normal?
If the problem automatically wakes up, I still don't understand why .. but I have experienced it in Ubuntu and in Arch (nothing to do with these dotfiles).

**Comment by xxxvik-xakerxxx** [comment]
Hi 
1 before I installed slim with your theme, it was just a dark screen, now I see batik wallpapers that are in your slim theme
I see a similar bug from another user, but transferring scripts to autostarts.sh did not help me 
2 sorry autolock
3 my device definitely does not have any third-party USB devices

**Comment by xxxvik-xakerxxx** [comment]
points 2 and 3 are not as important as 1)
at the same time, if I start the desktop, their parcellite menu will not work, but if I activate autostarts simply from the console with the bash .config/openbox/autostart command, then parcellite will work

**Comment by xxxvik-xakerxxx** [comment]
I fixed this error by commenting
session autolock
for xinitrc says there is no -g flag
and also brought autostart to autostart.sh
because that startx reported that there are problems with source
