### ISSUE TITLE
Rofi not workTitle [Bug]

### ISSUE THREAD

**Issue by CroissantDog** [owl4ce/dotfiles#98]
**Describe the bug**
When I click on app start icon, nothing happens. But if I click in the "Power Menu" Icon an error appears (image)

Rofi version: 1.5.1

 - **OS**: Debian 

![2021-05-04-194453_1920x1080_scrot](https://user-images.githubusercontent.com/50531405/117079003-4e060a00-ad11-11eb-9eda-1b6f5ab3a120.png)

**Comment by owl4ce** [comment]
duplicate https://github.com/owl4ce/dotfiles/issues/37

**Comment by sheeepdev** [comment]
@owl4ce You'd probably wan't to close this  issue now.

**Comment by owl4ce** [comment]
**Hi @CroissantDog**
Is now fixed?

**Comment by CroissantDog** [comment]
> **Hi @CroissantDog**
> Is now fixed?

Yes, I updated Rofi and now works fine.

Sorry for not updating the thread earlier
